// ข้อมูลหมวดหมู่ของ Session 2.2 — Output & Fluency Patterns
const Part22Data = [
    {
        id: 'A22', title: 'A. Clarifying & Confirming', color: 'bg-blue-50 border-blue-200 text-blue-900',
        sentences: [
            { en: "Just to confirm, the meeting is at 3 p.m., right?", th: "ขอยืนยันอีกทีนะ ประชุม 3 โมงเย็นใช่ไหม?" },
            { en: "So what you're saying is that the deadline is tomorrow?", th: "งั้นที่คุณพูดคือดีดไลน์คือพรุ่งนี้ใช่ไหม?" },
            { en: "Let me make sure I understand — you want me to redo the whole thing?", th: "ขอให้แน่ใจก่อนนะ คุณอยากให้ฉันทำทั้งหมดใหม่ใช่เปล่า?" },
            { en: "Can you clarify what you mean by that?", th: "ช่วยอธิบายให้ชัดขึ้นหน่อยได้ไหมว่าหมายความว่าอะไร?" },
            { en: "Do you mean the first version or the updated one?", th: "หมายถึงเวอร์ชันแรกหรือที่อัปเดตแล้ว?" },
            { en: "So if I understand correctly, we need to start over?", th: "งั้นถ้าฉันเข้าใจถูก เราต้องเริ่มใหม่ตั้งแต่ต้น?" },
            { en: "Sorry, could you say that again? I didn't quite catch it.", th: "โทษทีนะ ช่วยพูดอีกทีได้ไหม ฉันจับไม่ทัน" },
            { en: "Are you saying you want it by Friday or Monday?", th: "คุณหมายถึงอยากได้ภายในวันศุกร์หรือวันจันทร์?" },
            { en: "To be clear, I'm not able to commit to that timeline.", th: "พูดตรงๆ นะ ฉันไม่สามารถการันตีกำหนดนั้นได้" },
            { en: "Just to be sure, is this the final version?", th: "ขอให้ชัวร์ก่อนนะ นี่คือเวอร์ชันสุดท้ายแล้วใช่ไหม?" },
            { en: "I want to make sure we're on the same page.", th: "ฉันอยากให้แน่ใจว่าเราเข้าใจตรงกันนะ" },
            { en: "When you say 'soon', what exactly do you mean?", th: "ที่บอกว่า 'เร็วๆ นี้' หมายความว่าเมื่อไหร่กันแน่?" },
            { en: "Can you give me an example of what you mean?", th: "ช่วยยกตัวอย่างของที่คุณหมายถึงได้ไหม?" },
            { en: "So the next step is to submit the form, correct?", th: "งั้นขั้นตอนถัดไปคือยื่นฟอร์มใช่ไหม?" },
            { en: "I just want to double-check before I go ahead.", th: "ฉันแค่อยากเช็คอีกรอบก่อนดำเนินการต่อ" },
            { en: "Did you say Monday or Tuesday? I want to make sure.", th: "คุณบอกว่าวันจันทร์หรืออังคาร? อยากให้ชัวร์" },
            { en: "Let me repeat that back to you to make sure I got it.", th: "ให้ฉันทวนกลับไปหน่อยนะ เพื่อให้แน่ใจว่าเข้าใจถูก" },
            { en: "Could you be a bit more specific about what you need?", th: "ช่วยพูดให้เจาะจงขึ้นหน่อยได้ไหมว่าต้องการอะไร?" },
            { en: "Sorry to ask again, but I want to be absolutely sure.", th: "ขอโทษที่ถามซ้ำนะ แต่อยากให้ชัวร์แบบ 100%" },
            { en: "I think we might have a misunderstanding here.", th: "ฉันว่าเราอาจเข้าใจกันผิดอยู่นะ" },
        ]
    },
    {
        id: 'B22', title: 'B. Stalling & Buying Time', color: 'bg-orange-50 border-orange-200 text-orange-900',
        sentences: [
            { en: "That's a really good question. Let me think for a moment.", th: "คำถามดีมากเลย ขอคิดสักครู่นะ" },
            { en: "Let me think about that for a second.", th: "ให้ฉันคิดดูก่อนแป๊บนึงนะ" },
            { en: "Hmm, that's an interesting point.", th: "ฮืม นั่นเป็นประเด็นที่น่าสนใจนะ" },
            { en: "I'm not sure off the top of my head.", th: "ตอนนี้ยังนึกไม่ออกเลย" },
            { en: "I need a moment to collect my thoughts.", th: "ขอเวลาสักครู่เพื่อจัดความคิดก่อนนะ" },
            { en: "That's something I'd have to look into.", th: "นั่นเป็นเรื่องที่ฉันต้องไปหาข้อมูลก่อน" },
            { en: "Can I get back to you on that?", th: "ขอตอบคุณทีหลังได้ไหม?" },
            { en: "I want to give you a proper answer, so let me check first.", th: "ฉันอยากให้คำตอบที่ถูกต้อง ขอเช็คก่อนนะ" },
            { en: "Well, it's a bit complicated to explain.", th: "เอ่อ มันค่อนข้างซับซ้อนนิดหน่อยที่จะอธิบาย" },
            { en: "To be honest, I haven't thought about that yet.", th: "พูดตรงๆ นะ ฉันยังไม่ได้คิดถึงเรื่องนั้นเลย" },
            { en: "That's a fair point — I need to think it over.", th: "นั่นเป็นประเด็นที่สมเหตุสมผล ฉันต้องคิดทบทวนดูก่อน" },
            { en: "Let me rephrase that — I think I didn't say it clearly.", th: "ให้ฉันพูดใหม่นะ ฉันว่าพูดไม่ค่อยชัดเท่าไหร่" },
            { en: "Could you give me a day or two to think about it?", th: "ให้เวลาฉันคิดดูสักหนึ่งสองวันได้ไหม?" },
            { en: "I'll have to get back to you with a more detailed answer.", th: "ฉันจะตอบคุณพร้อมรายละเอียดที่ชัดกว่านี้ทีหลังนะ" },
            { en: "I'm still thinking through all the options.", th: "ฉันยังคิดทบทวนตัวเลือกทั้งหมดอยู่เลย" },
        ]
    },
    {
        id: 'C22', title: 'C. Transition Phrases', color: 'bg-indigo-50 border-indigo-200 text-indigo-900',
        sentences: [
            { en: "Having said that, I do think there's some truth to it.", th: "แต่ที่พูดมาทั้งหมด ฉันก็ยังคิดว่ามันมีความจริงอยู่บ้าง" },
            { en: "What I mean is that we need more time to prepare.", th: "ที่หมายความว่าคือ เราต้องการเวลาเตรียมตัวมากกว่านี้" },
            { en: "To be more specific, the issue is with the third section.", th: "พูดให้เจาะจงกว่านี้ ปัญหาอยู่ที่ส่วนที่สามนะ" },
            { en: "In other words, we have to start over.", th: "พูดอีกอย่างก็คือ เราต้องเริ่มใหม่" },
            { en: "That said, I'm still open to other ideas.", th: "ที่พูดมาทั้งหมดนั้น ฉันก็ยังเปิดรับไอเดียอื่นๆ อยู่นะ" },
            { en: "To put it simply, the plan didn't work.", th: "พูดง่ายๆ ก็คือ แผนนั้นไม่ได้ผล" },
            { en: "What's more, we're also behind on the budget.", th: "ยิ่งกว่านั้น งบประมาณก็ยังล่าช้าอยู่ด้วย" },
            { en: "On top of that, we have a deadline next week.", th: "นอกจากนั้นแล้ว เรายังมีดีดไลน์อาทิตย์หน้าด้วย" },
            { en: "At the same time, we can't ignore the other problems.", th: "ขณะเดียวกัน เราก็เพิกเฉยต่อปัญหาอื่นๆ ไม่ได้" },
            { en: "Having done that, let's move on to the next point.", th: "พอทำอันนั้นแล้ว มาต่อประเด็นถัดไปกันเลย" },
            { en: "With that in mind, let's reconsider the approach.", th: "โดยคำนึงถึงสิ่งนั้น มาทบทวนวิธีการใหม่กันดีกว่า" },
            { en: "All things considered, I think the first option is best.", th: "พิจารณาทุกอย่างแล้ว ฉันคิดว่าตัวเลือกแรกดีที่สุด" },
            { en: "That being said, we should still be careful.", th: "ถึงอย่างนั้น เราก็ยังต้องระวังอยู่ดี" },
            { en: "To sum up, we need more resources and more time.", th: "สรุปก็คือ เราต้องการทรัพยากรและเวลามากกว่านี้" },
            { en: "What I'm trying to say is that we need to communicate better.", th: "ที่ฉันพยายามจะบอกคือ เราต้องสื่อสารกันให้ดีขึ้นกว่านี้" },
            { en: "To get back to the original point...", th: "กลับมาที่ประเด็นตั้งต้นก่อนนะ..." },
            { en: "Building on what you just said...", th: "ต่อจากสิ่งที่คุณพูดมาเมื่อกี้..." },
            { en: "As I was saying before the interruption...", th: "อย่างที่ฉันกำลังพูดอยู่ก่อนถูกขัด..." },
            { en: "To wrap things up, here's the key takeaway.", th: "ก่อนจบ นี่คือสิ่งสำคัญที่อยากฝากไว้" },
            { en: "Apart from that, everything else seems fine.", th: "นอกจากนั้นแล้ว ทุกอย่างดูโอเคดี" },
        ]
    },
    {
        id: 'D22', title: 'D. Making & Responding to Requests', color: 'bg-yellow-50 border-yellow-200 text-yellow-900',
        sentences: [
            { en: "Would it be possible to move the meeting to Thursday?", th: "เป็นไปได้ไหมที่จะเลื่อนการประชุมไปวันพฤหัสฯ?" },
            { en: "Would it be okay if I took the afternoon off?", th: "โอเคไหมถ้าฉันจะลาครึ่งวันบ่าย?" },
            { en: "I'm afraid that won't be possible at the moment.", th: "ขอโทษนะ ตอนนี้คงทำแบบนั้นไม่ได้" },
            { en: "I'm sorry, but I'm not able to help with that right now.", th: "ขอโทษนะ ตอนนี้ฉันไม่สามารถช่วยเรื่องนั้นได้" },
            { en: "Of course — I'd be happy to help.", th: "แน่นอนเลย ยินดีช่วยอยู่แล้ว" },
            { en: "Leave it to me — I'll take care of it.", th: "ฝากฉันก็แล้วกัน ฉันจัดการให้" },
            { en: "I'll see what I can do.", th: "ฉันจะลองดูว่าจะทำอะไรได้บ้าง" },
            { en: "Is it okay if I send it to you tomorrow instead?", th: "โอเคไหมถ้าฉันจะส่งให้พรุ่งนี้แทน?" },
            { en: "Would you mind taking a look at this for me?", th: "รบกวนช่วยดูเรื่องนี้ให้ฉันหน่อยได้ไหม?" },
            { en: "I was hoping you could cover for me next Monday.", th: "ฉันหวังว่าคุณจะช่วยรับหน้าที่แทนฉันได้วันจันทร์หน้า" },
            { en: "I'll do my best, but I can't promise anything.", th: "ฉันจะพยายามให้ดีที่สุด แต่ไม่การันตีได้นะ" },
            { en: "Could you possibly have it ready by Friday?", th: "เป็นไปได้ไหมที่จะเตรียมให้พร้อมภายในวันศุกร์?" },
            { en: "That should be fine — give me until end of day.", th: "น่าจะโอเค ให้ถึงสิ้นวันก็แล้วกัน" },
            { en: "I'm not sure I can commit to that deadline.", th: "ฉันไม่แน่ใจว่าจะรับกำหนดนั้นได้" },
            { en: "I'd really appreciate your help on this.", th: "ฉันซาบซึ้งมากเลยถ้าคุณจะช่วยเรื่องนี้" },
            { en: "Do you think you could handle this while I'm away?", th: "คิดว่าคุณช่วยรับผิดชอบเรื่องนี้ตอนที่ฉันไม่อยู่ได้ไหม?" },
            { en: "I'll need a bit more time than expected.", th: "ฉันต้องการเวลามากกว่าที่คาดไว้นิดหน่อย" },
            { en: "No problem at all — consider it done.", th: "ไม่มีปัญหาเลย ทำให้เลย" },
            { en: "I'm afraid I already have a commitment that day.", th: "ขอโทษนะ วันนั้นฉันมีนัดไว้แล้ว" },
            { en: "I'll get right on it.", th: "ฉันจัดการให้เดี๋ยวนี้เลย" },
        ]
    },
    {
        id: 'E22', title: 'E. Agreeing & Disagreeing Politely', color: 'bg-green-50 border-green-200 text-green-900',
        sentences: [
            { en: "I completely see your point.", th: "ฉันเข้าใจมุมมองของคุณได้เลย" },
            { en: "I think you make a valid point.", th: "ฉันว่าคุณพูดถูกนะ มีเหตุผลดี" },
            { en: "I couldn't agree more.", th: "เห็นด้วยสุดๆ เลย" },
            { en: "That's exactly how I feel about it too.", th: "นั่นคือสิ่งที่ฉันรู้สึกด้วยเหมือนกัน" },
            { en: "You're absolutely right about that.", th: "คุณพูดถูกสุดๆ เรื่องนั้นเลย" },
            { en: "I see where you're coming from, but I'm not so sure.", th: "ฉันเข้าใจว่าคุณมาจากมุมไหน แต่ฉันไม่แน่ใจนัก" },
            { en: "I see your point, but have you considered the other side?", th: "ฉันเข้าใจประเด็นคุณ แต่คุณคิดถึงอีกด้านบ้างไหม?" },
            { en: "I'm not sure I agree with that entirely.", th: "ฉันไม่แน่ใจว่าเห็นด้วยกับเรื่องนั้นทั้งหมดนะ" },
            { en: "With respect, I think that's not quite right.", th: "พูดตรงๆ นะ ฉันคิดว่าเรื่องนั้นไม่ค่อยถูกต้อง" },
            { en: "I'm afraid I have to disagree on this one.", th: "เกรงว่าฉันต้องขอค้านเรื่องนี้นะ" },
            { en: "That's one way to look at it, but...", th: "นั่นเป็นมุมมองหนึ่ง แต่..." },
            { en: "I can see why you think that, but personally I feel differently.", th: "ฉันเข้าใจว่าทำไมคุณถึงคิดแบบนั้น แต่ฉันรู้สึกต่างออกไป" },
            { en: "You raise a fair point — I hadn't thought of it that way.", th: "คุณหยิบยกประเด็นที่ดีขึ้นมา ฉันยังไม่เคยคิดแบบนั้นเลย" },
            { en: "I agree in principle, but I think the details need work.", th: "เห็นด้วยในหลักการ แต่คิดว่ารายละเอียดยังต้องปรับ" },
            { en: "We'll just have to agree to disagree on this.", th: "เรื่องนี้คงต้องยอมรับว่าเห็นไม่ตรงกัน" },
            { en: "I think we're actually saying the same thing.", th: "ฉันว่าเราพูดถึงสิ่งเดียวกันอยู่นะ" },
            { en: "That's a fair point, and I hadn't considered that.", th: "นั่นเป็นประเด็นที่สมเหตุสมผล และฉันยังไม่ได้คิดถึงตรงนั้น" },
            { en: "I understand your concern, but I still think we should proceed.", th: "ฉันเข้าใจความกังวลของคุณ แต่ฉันยังคิดว่าเราควรดำเนินการต่อ" },
            { en: "You make a good point, but I'm not 100% convinced.", th: "คุณพูดถูกนะ แต่ฉันยังไม่ค่อยแน่ใจ 100%" },
            { en: "I partly agree, but there's more to it than that.", th: "ฉันเห็นด้วยบางส่วน แต่มันมีมากกว่านั้น" },
        ]
    },
    {
        id: 'F22', title: 'F. Describing Processes & Steps', color: 'bg-teal-50 border-teal-200 text-teal-900',
        sentences: [
            { en: "First, you need to create an account.", th: "อันดับแรก คุณต้องสร้างบัญชีก่อน" },
            { en: "Once you've done that, click on the settings icon.", th: "พอทำอันนั้นแล้ว ให้กดที่ไอคอน settings" },
            { en: "The next step is to fill in your personal details.", th: "ขั้นตอนต่อไปคือกรอกข้อมูลส่วนตัว" },
            { en: "After that, you'll receive a confirmation email.", th: "หลังจากนั้น คุณจะได้รับอีเมลยืนยัน" },
            { en: "Finally, click 'Submit' and you're done.", th: "สุดท้าย กด 'Submit' แล้วก็เสร็จแล้ว" },
            { en: "The whole process takes about 10 minutes.", th: "ทั้งกระบวนการใช้เวลาประมาณ 10 นาที" },
            { en: "Before you start, make sure you have all the documents ready.", th: "ก่อนเริ่ม ให้แน่ใจว่าเตรียมเอกสารทั้งหมดไว้ครบ" },
            { en: "You can skip this step if you've done it before.", th: "คุณข้ามขั้นตอนนี้ได้ถ้าเคยทำมาแล้ว" },
            { en: "Make sure to save your work at each step.", th: "อย่าลืมเซฟงานในแต่ละขั้นตอนนะ" },
            { en: "If something goes wrong, just start from the beginning.", th: "ถ้ามีอะไรผิดพลาด ก็แค่เริ่มใหม่ตั้งแต่ต้น" },
            { en: "Repeat these steps until you get the result you want.", th: "ทำซ้ำขั้นตอนพวกนี้จนกว่าจะได้ผลลัพธ์ที่ต้องการ" },
            { en: "The process is quite straightforward once you get the hang of it.", th: "กระบวนการนี้ค่อนข้างตรงไปตรงมาพอจับทางได้แล้ว" },
            { en: "Let me walk you through it step by step.", th: "ให้ฉันพาคุณทำทีละขั้นตอนนะ" },
            { en: "At this stage, you should see a pop-up window appear.", th: "ในขั้นตอนนี้ คุณควรจะเห็นหน้าต่าง pop-up ขึ้นมา" },
            { en: "Once everything is in order, submit the form.", th: "พอทุกอย่างเรียบร้อยแล้ว ก็ยื่นฟอร์มได้เลย" },
        ]
    },
    {
        id: 'G22', title: 'G. Giving & Responding to News', color: 'bg-fuchsia-50 border-fuchsia-200 text-fuchsia-900',
        sentences: [
            { en: "I have some good news — I got the job!", th: "ฉันมีข่าวดีนะ ฉันได้งานแล้ว!" },
            { en: "Oh, that's such a relief to hear!", th: "โอ้ โล่งอกมากเลยที่ได้ยินแบบนี้!" },
            { en: "I'm so happy for you — you deserve it!", th: "ดีใจให้มากเลยนะ คุณสมควรได้รับ!" },
            { en: "I'm sorry to hear that — are you okay?", th: "เสียใจที่ได้ยินนะ คุณโอเคไหม?" },
            { en: "That's terrible news — I hope things get better soon.", th: "ข่าวร้ายมากเลย หวังว่าทุกอย่างจะดีขึ้นเร็วๆ นี้นะ" },
            { en: "That's amazing — congratulations!", th: "ยอดเยี่ยมมากเลย ขอแสดงความยินดีด้วย!" },
            { en: "I can't believe it — that's incredible!", th: "เชื่อไม่ได้เลย สุดยอดมาก!" },
            { en: "Oh no, that's really unfortunate.", th: "โอ้ไม่ นั่นโชคร้ายจริงๆ เลยนะ" },
            { en: "What a surprise — I didn't see that coming.", th: "น่าประหลาดใจมาก ฉันไม่ทันนึกเลย" },
            { en: "That must be really hard for you.", th: "นั่นคงลำบากมากสำหรับคุณเลยนะ" },
            { en: "I'm glad things worked out in the end.", th: "ดีใจที่ทุกอย่างลงเอยได้ดี" },
            { en: "Did you hear about what happened to Arm?", th: "ได้ยินเรื่องที่เกิดกับอาร์มไหม?" },
            { en: "Guess what — I'm moving to a new place!", th: "เดาอะไรสิ ฉันกำลังจะย้ายที่อยู่ใหม่!" },
            { en: "You're not going to believe this, but I passed.", th: "คุณคงไม่เชื่อหรอก แต่ฉันผ่านมาได้" },
            { en: "I have some bad news — the event's been cancelled.", th: "มีข่าวร้ายนิดนึง งานถูกยกเลิกแล้ว" },
            { en: "How did it go? I've been waiting to hear!", th: "เป็นยังไงบ้าง? ฉันรอฟังอยู่เลย!" },
            { en: "That's the best news I've heard all week.", th: "นั่นเป็นข่าวดีที่สุดที่ได้ยินทั้งสัปดาห์เลย" },
            { en: "I'm not sure how to feel about that, honestly.", th: "จริงๆ แล้วฉันยังไม่รู้จะรู้สึกยังไงกับเรื่องนั้นเลย" },
            { en: "Wow, that came out of nowhere.", th: "ว้าว นั่นมาแบบไม่มีลางบอกเหตุเลยนะ" },
            { en: "That's so exciting — tell me everything!", th: "ตื่นเต้นมากเลย เล่าให้ฟังทั้งหมดเลยสิ!" },
        ]
    },
    {
        id: 'H22', title: 'H. Small Talk Extenders', color: 'bg-sky-50 border-sky-200 text-sky-900',
        sentences: [
            { en: "Speaking of which, how did your interview go?", th: "พูดถึงเรื่องนั้น สัมภาษณ์งานไปเป็นยังไงบ้าง?" },
            { en: "That reminds me — I've been meaning to ask you something.", th: "นั่นทำให้ฉันนึกขึ้นได้ ฉันอยากถามคุณเรื่องนึงมาสักพักแล้ว" },
            { en: "Oh, I know exactly what you mean.", th: "โอ้ ฉันเข้าใจที่คุณหมายถึงเป๊ะเลย" },
            { en: "That's funny — the same thing happened to me last week.", th: "ตลกดีนะ เรื่องเดียวกันเกิดกับฉันอาทิตย์ที่แล้วพอดี" },
            { en: "Really? I had no idea. Tell me more.", th: "จริงเหรอ? ฉันไม่รู้เลย เล่าให้ฟังเพิ่มสิ" },
            { en: "I was just thinking the same thing!", th: "ฉันเพิ่งคิดเรื่องเดียวกันนั้นอยู่เลย!" },
            { en: "That's a coincidence — I was just talking about that.", th: "เป็นเรื่องบังเอิญมากเลย ฉันเพิ่งพูดถึงเรื่องนั้นอยู่พอดี" },
            { en: "By the way, have you tried the new café downtown?", th: "อ้อ แวะถามหน่อย คุณเคยลองร้านกาแฟใหม่ในเมืองไหม?" },
            { en: "Anyway, how have you been lately?", th: "เอาล่ะ ช่วงนี้เป็นยังไงบ้าง?" },
            { en: "That said, I think everything will work out fine.", th: "ถึงอย่างนั้น ฉันก็คิดว่าทุกอย่างจะลงเอยด้วยดี" },
            { en: "I know right? It's been so busy lately.", th: "ใช่ไหมล่ะ ช่วงนี้ยุ่งมากเลย" },
            { en: "On a different note, any plans for the weekend?", th: "เปลี่ยนเรื่องหน่อยนะ สุดสัปดาห์มีแผนอะไรบ้าง?" },
            { en: "Actually, now that I think about it, me too.", th: "จริงๆ แล้ว พอคิดดูก็ ฉันก็เหมือนกันนะ" },
            { en: "I keep forgetting to ask — how's your family?", th: "ฉันลืมถามมาตลอด ครอบครัวเป็นยังไงบ้าง?" },
            { en: "Time flies, doesn't it? I can't believe it's already December.", th: "เวลามันผ่านเร็วมากนะ เชื่อไม่ได้เลยว่าเดือนธันวาแล้ว" },
        ]
    },
    {
        id: 'I22', title: 'I. Apologizing & Explaining', color: 'bg-red-50 border-red-200 text-red-900',
        sentences: [
            { en: "I'm really sorry for the late reply.", th: "ขอโทษมากนะที่ตอบกลับช้า" },
            { en: "I apologize for any inconvenience this may have caused.", th: "ขออภัยสำหรับความไม่สะดวกที่เกิดขึ้น" },
            { en: "I'm sorry — that was completely my fault.", th: "ขอโทษนะ นั่นเป็นความผิดฉันล้วนๆ" },
            { en: "Please accept my sincere apologies.", th: "ขอให้รับคำขอโทษอย่างจริงใจจากฉันด้วยนะ" },
            { en: "I owe you an apology — I shouldn't have done that.", th: "ฉันต้องขอโทษคุณ ไม่น่าทำแบบนั้นเลย" },
            { en: "I didn't mean to upset you — I'm truly sorry.", th: "ฉันไม่ได้ตั้งใจให้คุณหงุดหงิด ขอโทษจริงๆ นะ" },
            { en: "I should have let you know sooner — my mistake.", th: "ฉันน่าจะแจ้งคุณก่อนหน้านี้ ผิดฉันเอง" },
            { en: "I take full responsibility for what happened.", th: "ฉันรับผิดชอบในสิ่งที่เกิดขึ้นทั้งหมด" },
            { en: "It won't happen again — I'll make sure of it.", th: "จะไม่เกิดขึ้นอีกแล้ว ฉันจะดูแลให้ดี" },
            { en: "The reason I didn't respond was because I was in a meeting.", th: "สาเหตุที่ฉันไม่ได้ตอบเพราะกำลังประชุมอยู่" },
            { en: "I had a family emergency — I'm sorry for the short notice.", th: "มีเรื่องฉุกเฉินในครอบครัว ขอโทษที่แจ้งกะทันหัน" },
            { en: "I was under the impression that someone else was handling it.", th: "ฉันเข้าใจว่ามีคนอื่นดูแลอยู่แล้ว" },
            { en: "I know this isn't ideal, and I'm working on fixing it.", th: "ฉันรู้ว่ามันไม่ดีเลย และกำลังหาทางแก้อยู่" },
            { en: "I appreciate your patience while we sort this out.", th: "ขอบคุณที่อดทนรอขณะที่เราจัดการเรื่องนี้" },
            { en: "There seems to have been a miscommunication somewhere.", th: "ดูเหมือนจะมีการสื่อสารผิดพลาดเกิดขึ้นที่ไหนซักที่" },
            { en: "I'm sorry for the confusion — let me clear this up.", th: "ขอโทษที่ทำให้งง มาทำให้กระจ่างกันเลยนะ" },
            { en: "I realize now that I misunderstood the situation.", th: "ตอนนี้ฉันรู้แล้วว่าฉันเข้าใจสถานการณ์ผิด" },
            { en: "I should have double-checked before sending that.", th: "น่าจะเช็คซ้ำก่อนส่งเรื่องนั้น" },
            { en: "I'm sorry for taking up so much of your time.", th: "ขอโทษที่ใช้เวลาของคุณไปมากนะ" },
            { en: "No hard feelings — it was a misunderstanding on my part.", th: "ไม่ได้โกรธกันนะ มันเป็นความเข้าใจผิดของฉันเอง" },
        ]
    },
    {
        id: 'J22', title: 'J. Ending Conversations Naturally', color: 'bg-amber-50 border-amber-200 text-amber-900',
        sentences: [
            { en: "I'll let you get back to what you were doing.", th: "ให้คุณกลับไปทำสิ่งที่ค้างไว้ได้เลยนะ" },
            { en: "Let's catch up properly soon.", th: "ไว้หาเวลานั่งคุยกันจริงๆ จังๆ นะ" },
            { en: "We should do this again sometime.", th: "ไว้หาโอกาสทำแบบนี้อีกนะ" },
            { en: "It was really nice talking to you.", th: "สนุกมากเลยที่ได้คุยกัน" },
            { en: "I've really got to run — I'll message you later.", th: "ฉันต้องไปแล้วจริงๆ ไว้ทักไปทีหลังนะ" },
            { en: "I'll be in touch soon.", th: "ไว้ติดต่อกันเร็วๆ นี้นะ" },
            { en: "Talk soon — take care of yourself.", th: "ไว้คุยกันนะ ดูแลตัวเองด้วย" },
            { en: "I should probably get going now.", th: "น่าจะได้เดินทางได้แล้วนะตอนนี้" },
            { en: "It's been great seeing you again.", th: "ดีใจมากที่ได้เจอกันอีกครั้ง" },
            { en: "We'll have to do this more often.", th: "ต้องทำแบบนี้บ่อยๆ เลยนะ" },
            { en: "Anyway, I should go — it was good to catch up.", th: "เอาล่ะ ฉันต้องไปแล้ว ดีมากที่ได้คุยกัน" },
            { en: "Keep me posted on how things go.", th: "อัปเดตให้ฟังด้วยนะว่าเป็นยังไง" },
            { en: "Let me know if you need anything.", th: "ต้องการอะไรบอกได้เลยนะ" },
            { en: "Thanks for everything — I really appreciate it.", th: "ขอบคุณทุกอย่างนะ ซาบซึ้งมากจริงๆ" },
            { en: "I'll reach out once I have more information.", th: "ฉันจะติดต่อไปพอมีข้อมูลเพิ่มเติมนะ" },
        ]
    },
];

window.ESB_Sessions.push({
    id: 'session-2-2',
    title: 'Session 2.2: Output & Fluency Patterns',
    data: Part22Data,
    defaultOpen: false
});


