// ข้อมูลหมวดหมู่ของ Session 1
const Part1Data = [
    {
        id: 'A', title: 'A. Greetings & General Small Talk', color: 'bg-blue-100 border-blue-200 text-blue-800',
        sentences: [
            { en: "How are you?", th: "สบายดีไหม?" }, { en: "How are you doing?", th: "เป็นไงบ้าง?" }, { en: "How are you today?", th: "วันนี้เป็นไงบ้าง?" }, { en: "How is it going?", th: "ความเป็นอยู่เป็นไงบ้าง?" }, { en: "How is everything?", th: "ทุกอย่างเป็นไงบ้าง?" }, { en: "How's life?", th: "ชีวิตเป็นไงบ้าง?" }, { en: "What’s up?", th: "ว่าไง / มีไรเปล่า?" }, { en: "What’s new?", th: "มีอะไรใหม่ๆ บ้างไหม?" }, { en: "What’s happening?", th: "เกิดอะไรขึ้น / ทำไรอยู่?" }, { en: "What are you up to?", th: "ทำอะไรอยู่บ้างช่วงนี้?" }, { en: "What are you doing right now?", th: "ตอนนี้ทำอะไรอยู่?" }, { en: "It’s good to see you.", th: "ดีใจที่ได้เจอกันนะ" }, { en: "It’s nice to meet you.", th: "ยินดีที่ได้รู้จัก" }, { en: "It’s been a long time.", th: "ไม่ได้เจอกันนานเลยนะ" }, { en: "I’m fine, thanks.", th: "ฉันสบายดี ขอบใจนะ" }, { en: "I’m doing well.", th: "ฉันสบายดี" }, { en: "I’m pretty good.", th: "ก็ค่อนข้างดีนะ" }, { en: "I’m doing okay.", th: "ฉันก็โอเคนะ" }, { en: "I’m not bad.", th: "ก็ไม่แย่นะ" }, { en: "I’m a bit tired today.", th: "วันนี้ฉันเหนื่อยนิดหน่อย" }, { en: "I’m so busy these days.", th: "ช่วงนี้ฉันยุ่งมาก" }, { en: "Everything is fine.", th: "ทุกอย่างเรียบร้อยดี" }, { en: "Everything is great.", th: "ทุกอย่างโอเคมาก" }, { en: "Same as usual.", th: "ก็เหมือนเดิมแหละ" }, { en: "Can’t complain.", th: "ก็เรื่อยๆ (ไม่มีไรให้บ่น)" }, { en: "You look great.", th: "คุณดูดีจัง" }, { en: "You look tired.", th: "คุณดูเหนื่อยๆ นะ" }, { en: "You look happy today.", th: "วันนี้คุณดูมีความสุขนะ" }
        ]
    },
    {
        id: 'B', title: 'B. Daily Routines & Habits', color: 'bg-yellow-100 border-yellow-200 text-yellow-800',
        sentences: [
            { en: "I get up early every day.", th: "ฉันตื่นเช้าทุกวัน" }, { en: "I usually get up at 7 a.m.", th: "ปกติฉันตื่น 7 โมงเช้า" }, { en: "I always wake up late on weekends.", th: "ฉันตื่นสายตลอดช่วงสุดสัปดาห์" }, { en: "I make my bed every morning.", th: "ฉันเก็บที่นอนทุกเช้า" }, { en: "I brush my teeth twice a day.", th: "ฉันแปรงฟันวันละ 2 ครั้ง" }, { en: "I take a shower in the morning.", th: "ฉันอาบน้ำตอนเช้า" }, { en: "I get dressed quickly.", th: "ฉันแต่งตัวอย่างรวดเร็ว" }, { en: "I usually drink coffee.", th: "ปกติฉันดื่มกาแฟ" }, { en: "I drink coffee every morning.", th: "ฉันดื่มกาแฟทุกเช้า" }, { en: "I don't drink coffee.", th: "ฉันไม่ดื่มกาแฟ" }, { en: "I don't usually eat breakfast.", th: "ปกติฉันไม่กินมื้อเช้า" }, { en: "I have lunch at noon.", th: "ฉันกินมื้อเที่ยงตอนเที่ยงตรง" }, { en: "I leave the house at 8 a.m.", th: "ฉันออกจากบ้านตอน 8 โมง" }, { en: "I drive to work.", th: "ฉันขับรถไปทำงาน" }, { en: "I take the bus to school.", th: "ฉันนั่งรถเมล์ไปโรงเรียน" }, { en: "I walk to the station.", th: "ฉันเดินไปสถานี" }, { en: "I come home late.", th: "ฉันกลับบ้านดึก" }, { en: "I usually cook dinner.", th: "ปกติฉันทำมื้อเย็นกินเอง" }, { en: "I watch TV in the evening.", th: "ฉันดูทีวีตอนเย็น" }, { en: "I read a book before bed.", th: "ฉันอ่านหนังสือก่อนนอน" }, { en: "I go to sleep at midnight.", th: "ฉันเข้านอนตอนเที่ยงคืน" }, { en: "What time do you get up?", th: "คุณตื่นนอนกี่โมง?" }, { en: "What time do you leave?", th: "คุณออก(จากบ้าน)กี่โมง?" }, { en: "What time do you go to bed?", th: "คุณเข้านอนกี่โมง?" }, { en: "Do you exercise?", th: "คุณออกกำลังกายไหม?" }, { en: "Do you work out every day?", th: "คุณออกกำลังกายทุกวันไหม?" }, { en: "Do you cook at home?", th: "คุณทำกับข้าวที่บ้านไหม?" }, { en: "Do you take the bus?", th: "คุณนั่งรถเมล์หรือเปล่า?" }, { en: "How do you get to work?", th: "คุณไปทำงานยังไง?" }, { en: "How often do you clean your room?", th: "คุณทำความสะอาดห้องบ่อยไหม?" }
        ]
    },
    {
        id: 'C', title: 'C. Study & Work', color: 'bg-orange-100 border-orange-200 text-orange-800',
        sentences: [
            { en: "I work in an office.", th: "ฉันทำงานในออฟฟิศ" }, { en: "I work for a big company.", th: "ฉันทำงานบริษัทใหญ่" }, { en: "I work from home today.", th: "วันนี้ฉันทำงานที่บ้าน" }, { en: "I'm working right now.", th: "ตอนนี้ฉันทำงานอยู่" }, { en: "I'm busy with work.", th: "ฉันยุ่งเรื่องงานอยู่" }, { en: "I'm in a meeting.", th: "ฉันติดประชุมอยู่" }, { en: "I have a meeting at 10.", th: "ฉันมีประชุมตอน 10 โมง" }, { en: "I have a lot of work to do.", th: "ฉันมีงานต้องทำเยอะมาก" }, { en: "I study English every day.", th: "ฉันเรียนภาษาอังกฤษทุกวัน" }, { en: "I'm studying for a test.", th: "ฉันกำลังติวสอบอยู่" }, { en: "I'm learning Spanish.", th: "ฉันกำลังเรียนภาษาสเปน" }, { en: "It’s very difficult.", th: "มันยากมาก" }, { en: "It’s not easy.", th: "มันไม่ง่ายเลย" }, { en: "It takes a long time.", th: "มันใช้เวลานาน" }, { en: "My boss is nice.", th: "หัวหน้าฉันนิสัยดี" }, { en: "My colleagues are friendly.", th: "เพื่อนร่วมงานเป็นกันเอง" }, { en: "Do you work today?", th: "วันนี้ทำงานไหม?" }, { en: "Do you like your job?", th: "คุณชอบงานของคุณไหม?" }, { en: "Do you have a lot of homework?", th: "การบ้านเยอะไหม?" }, { en: "What do you do?", th: "คุณทำงานอะไร?" }, { en: "What do you do for a living?", th: "คุณทำอาชีพอะไร?" }, { en: "Where do you work?", th: "คุณทำงานที่ไหน?" }, { en: "Which school do you go to?", th: "คุณเรียนโรงเรียนไหน?" }, { en: "Are you busy?", th: "ยุ่งอยู่ไหม?" }, { en: "Are you still working?", th: "ยังทำงานอยู่เหรอ?" }, { en: "When does the meeting start?", th: "ประชุมเริ่มกี่โมง?" }, { en: "When does the class finish?", th: "เลิกเรียนกี่โมง?" }
        ]
    },
    {
        id: 'D', title: 'D. Friends & Social Life', color: 'bg-indigo-100 border-indigo-200 text-indigo-800',
        sentences: [
            { en: "Do you want to go out?", th: "อยากออกไปข้างนอกไหม?" }, { en: "Do you want to join us?", th: "อยากไปด้วยกันไหม?" }, { en: "Do you want to come over?", th: "อยากแวะมาหาไหม?" }, { en: "Do you want to grab coffee?", th: "ไปดื่มกาแฟกันไหม?" }, { en: "Do you have time?", th: "มีเวลาไหม?" }, { en: "Do you have plans tonight?", th: "คืนนี้มีแผนทำอะไรหรือยัง?" }, { en: "Are you free this weekend?", th: "สุดสัปดาห์นี้ว่างไหม?" }, { en: "Are you free later?", th: "เดี๋ยวว่างไหม (หลังจากนี้)?" }, { en: "Are you ready to go?", th: "พร้อมไปหรือยัง?" }, { en: "Can you make it?", th: "คุณมาได้ไหม / สะดวกไหม?" }, { en: "Let’s go.", th: "ไปกันเถอะ" }, { en: "Let’s meet up.", th: "มาเจอกันหน่อยไหม" }, { en: "Let’s hang out.", th: "ไปเที่ยวเล่น/สังสรรค์กันเถอะ" }, { en: "Let’s grab a drink.", th: "ไปหาอะไรดื่มกันเถอะ" }, { en: "Let’s do something fun.", th: "หาอะไรสนุกๆ ทำกันเถอะ" }, { en: "I’m free today.", th: "วันนี้ฉันว่าง" }, { en: "I’m busy tonight.", th: "คืนนี้ฉันไม่ว่าง" }, { en: "I’m hanging out with friends.", th: "ฉันกำลังสังสรรค์กับเพื่อน" }, { en: "I’m waiting for a friend.", th: "ฉันกำลังรอเพื่อนอยู่" }, { en: "We are having a party.", th: "พวกเรากำลังมีปาร์ตี้กัน" }, { en: "Where are you?", th: "คุณอยู่ที่ไหน?" }, { en: "Where are we going?", th: "เรากำลังจะไปไหนกัน?" }, { en: "Who are you with?", th: "คุณอยู่กับใคร?" }, { en: "Who is coming?", th: "ใครจะมาบ้าง?" }, { en: "How about dinner?", th: "ไปกินมื้อเย็นกันไหม?" }, { en: "How about a movie?", th: "ดูหนังกันไหม?" }
        ]
    },
    {
        id: 'E', title: 'E. Feelings, Opinions & Preferences', color: 'bg-purple-100 border-purple-200 text-purple-800',
        sentences: [
            { en: "I like it.", th: "ฉันชอบนะ" }, { en: "I really like it.", th: "ฉันชอบมันมาก" }, { en: "I love this song.", th: "ฉันรักเพลงนี้" }, { en: "I enjoy reading.", th: "ฉันสนุกกับการอ่าน" }, { en: "I prefer tea.", th: "ฉันชอบชามากกว่า" }, { en: "I don't like it.", th: "ฉันไม่ชอบเลย" }, { en: "I hate waiting.", th: "ฉันเกลียดการรอคอย" }, { en: "I don't care.", th: "ฉันไม่แคร์ / ไม่สน" }, { en: "I don't mind.", th: "ฉันไม่ถือสา / ไม่ติดขัดอะไร" }, { en: "It doesn't matter.", th: "ไม่สำคัญหรอก / ช่างเถอะ" }, { en: "I feel happy.", th: "ฉันมีความสุข" }, { en: "I feel sad.", th: "ฉันเศร้า" }, { en: "I feel tired.", th: "ฉันรู้สึกเหนื่อย" }, { en: "I feel sick.", th: "ฉันรู้สึกป่วย" }, { en: "I feel better now.", th: "ฉันรู้สึกดีขึ้นแล้ว" }, { en: "I think so.", th: "ฉันก็คิดงั้นนะ" }, { en: "I don't think so.", th: "ฉันไม่คิดงั้นนะ" }, { en: "I think it’s good.", th: "ฉันว่ามันก็ดีนะ" }, { en: "I think it’s too expensive.", th: "ฉันว่ามันแพงไป" }, { en: "I believe you.", th: "ฉันเชื่อคุณ" }, { en: "I agree with you.", th: "ฉันเห็นด้วยกับคุณ" }, { en: "I totally agree.", th: "ฉันเห็นด้วยสุดๆ" }, { en: "I disagree.", th: "ฉันไม่เห็นด้วย" }, { en: "Do you like it?", th: "คุณชอบไหม?" }, { en: "Do you think it’s okay?", th: "คุณคิดว่ามันโอเคไหม?" }, { en: "What do you think?", th: "คุณคิดว่าไง?" }, { en: "What do you prefer?", th: "คุณชอบอันไหนมากกว่า?" }, { en: "How do you feel?", th: "คุณรู้สึกยังไง?" }
        ]
    },
    {
        id: 'F', title: 'F. Asking for & Giving Information', color: 'bg-red-100 border-red-200 text-red-800',
        sentences: [
            { en: "Excuse me.", th: "ขอโทษนะครับ/คะ" }, { en: "Do you speak English?", th: "คุณพูดภาษาอังกฤษได้ไหม?" }, { en: "Do you understand?", th: "คุณเข้าใจไหม?" }, { en: "Do you know him?", th: "คุณรู้จักเขาไหม?" }, { en: "Do you know where it is?", th: "รู้ไหมว่ามันอยู่ที่ไหน?" }, { en: "Do you know what time it is?", th: "รู้ไหมว่ากี่โมงแล้ว?" }, { en: "Does this bus go to the city?", th: "รถเมล์คันนี้เข้าเมืองไหม?" }, { en: "Is this seat free?", th: "ที่ตรงนี้ว่างไหม?" }, { en: "Is it open?", th: "มันเปิดอยู่ไหม?" }, { en: "Is it far from here?", th: "ไกลจากที่นี่ไหม?" }, { en: "Where is the bathroom?", th: "ห้องน้ำอยู่ที่ไหน?" }, { en: "Where is the nearest station?", th: "สถานีที่ใกล้ที่สุดอยู่ที่ไหน?" }, { en: "Where is the exit?", th: "ทางออกอยู่ที่ไหน?" }, { en: "What is this?", th: "นี่คืออะไร?" }, { en: "What does this mean?", th: "นี่หมายความว่าอะไร?" }, { en: "What is the password?", th: "รหัสผ่านคืออะไร?" }, { en: "How much is it?", th: "ราคาเท่าไหร่?" }, { en: "How much does it cost?", th: "มันราคาเท่าไหร่?" }, { en: "How long does it take?", th: "ใช้เวลานานแค่ไหน?" }, { en: "The bank is closed.", th: "ธนาคารปิดแล้ว" }, { en: "The store is open.", th: "ร้านเปิดอยู่" }, { en: "It is on the right.", th: "มันอยู่ทางขวา" }, { en: "It is on the left.", th: "มันอยู่ทางซ้าย" }, { en: "It is next to the hotel.", th: "มันอยู่ติดกับโรงแรม" }
        ]
    },
    {
        id: 'G', title: 'G. Offers, Requests & Permission', color: 'bg-green-100 border-green-200 text-green-800',
        sentences: [
            { en: "Can I help you?", th: "ให้ฉันช่วยไหม?" }, { en: "Can I ask a question?", th: "ขอถามอะไรหน่อยได้ไหม?" }, { en: "Can I use your phone?", th: "ขอยืมโทรศัพท์หน่อยได้ไหม?" }, { en: "Can I sit here?", th: "ขอนั่งตรงนี้ได้ไหม?" }, { en: "Can I get a glass of water?", th: "ขอน้ำสักแก้วได้ไหม?" }, { en: "Can I have the bill, please?", th: "เช็คบิลด้วยครับ/ค่ะ" }, { en: "Can you help me?", th: "ช่วยฉันหน่อยได้ไหม?" }, { en: "Can you repeat that?", th: "ช่วยพูดอีกทีได้ไหม?" }, { en: "Can you speak slower?", th: "พูดช้าลงหน่อยได้ไหม?" }, { en: "Can you open the window?", th: "ช่วยเปิดหน้าต่างหน่อยได้ไหม?" }, { en: "Can you explain this?", th: "ช่วยอธิบายอันนี้หน่อยได้ไหม?" }, { en: "Could you do me a favor?", th: "ช่วยอะไรฉันสักอย่างได้ไหม?" }, { en: "Do you need anything?", th: "ต้องการอะไรไหม?" }, { en: "Do you need help?", th: "ต้องการความช่วยเหลือไหม?" }, { en: "Do you want some water?", th: "เอาน้ำหน่อยไหม?" }, { en: "Would you like to come?", th: "อยากมาด้วยกันไหม?" }, { en: "I can do it.", th: "ฉันทำได้" }, { en: "I can’t do it.", th: "ฉันทำไม่ได้" }, { en: "I can’t find my keys.", th: "ฉันหากุญแจไม่เจอ" }, { en: "I can’t hear you.", th: "ฉันไม่ได้ยินคุณ" }, { en: "You can park here.", th: "คุณจอดรถตรงนี้ได้" }, { en: "You can’t smoke here.", th: "ห้ามสูบบุหรี่ตรงนี้" }
        ]
    },
    {
        id: 'H', title: 'H. Plans & Arrangements', color: 'bg-teal-100 border-teal-200 text-teal-800',
        sentences: [
            { en: "What are you doing tomorrow?", th: "พรุ่งนี้คุณจะทำอะไร?" }, { en: "What are you doing this weekend?", th: "สุดสัปดาห์นี้ทำอะไร?" }, { en: "Are you doing anything special?", th: "มีทำอะไรพิเศษไหม?" }, { en: "I’m staying home today.", th: "วันนี้ฉันจะอยู่บ้าน" }, { en: "I’m going shopping.", th: "ฉันจะไปช้อปปิ้ง" }, { en: "I’m meeting a friend.", th: "ฉันนัดเพื่อนไว้" }, { en: "I’m visiting my parents.", th: "ฉันจะไปหาพ่อแม่" }, { en: "I’m traveling to Japan.", th: "ฉันกำลังจะไปเที่ยวญี่ปุ่น" }, { en: "I’m going to clean my room.", th: "ฉันกะว่าจะทำความสะอาดห้อง" }, { en: "I’m going to cook dinner.", th: "ฉันกะว่าจะทำมื้อเย็น" }, { en: "I’m going to be late.", th: "ฉันน่าจะไปสาย" }, { en: "I’m going to buy a new phone.", th: "ฉันจะซื้อโทรศัพท์ใหม่" }, { en: "We are leaving soon.", th: "พวกเราจะไปเร็วๆ นี้แหละ" }, { en: "We are moving house next week.", th: "เราจะย้ายบ้านอาทิตย์หน้า" }, { en: "We are planning a trip.", th: "เรากำลังวางแผนเที่ยวกัน" }, { en: "I plan to study abroad.", th: "ฉันวางแผนจะไปเรียนต่อนอก" }, { en: "I want to go there.", th: "ฉันอยากไปที่นั่น" }, { en: "I need to go now.", th: "ฉันต้องไปแล้ว" }, { en: "I have to go.", th: "ฉันจำเป็นต้องไป" }, { en: "I don't want to go.", th: "ฉันไม่อยากไป" }
        ]
    },
    {
        id: 'I', title: 'I. Online, Phone & Chat', color: 'bg-cyan-100 border-cyan-200 text-cyan-800',
        sentences: [
            { en: "Can you hear me?", th: "ได้ยินฉันไหม?" }, { en: "Can you see me?", th: "เห็นฉันไหม?" }, { en: "Can you see my screen?", th: "เห็นหน้าจอฉันไหม?" }, { en: "The connection is bad.", th: "สัญญาณไม่ดีเลย" }, { en: "The internet is slow.", th: "เน็ตช้ามาก" }, { en: "You are breaking up.", th: "เสียงคุณขาดๆ หายๆ" }, { en: "You are on mute.", th: "คุณปิดไมค์อยู่" }, { en: "I’m calling you now.", th: "ฉันกำลังโทรหาคุณ" }, { en: "I’m texting you.", th: "ฉันกำลังส่งข้อความหาคุณ" }, { en: "I’m sending an email.", th: "ฉันกำลังส่งอีเมล" }, { en: "I’m waiting for your reply.", th: "ฉันรอคุณตอบอยู่นะ" }, { en: "Let me check my phone.", th: "ขอเช็คโทรศัพท์แป๊บ" }, { en: "Let me Google it.", th: "เดี๋ยวขอลองกูเกิลดูก่อน" }, { en: "Check your inbox.", th: "เช็คกล่องข้อความหน่อย" }, { en: "Send me the link.", th: "ส่งลิงก์มาให้หน่อย" }, { en: "Text me later.", th: "ส่งข้อความมาทีหลังนะ" }, { en: "Call me back.", th: "โทรกลับด้วยนะ" }, { en: "My battery is low.", th: "แบตเตอรี่ฉันต่ำแล้ว" }, { en: "My phone is dead.", th: "มือถือฉันแบตหมด" }
        ]
    },
    {
        id: 'J', title: 'J. Problems & Complaints', color: 'bg-rose-100 border-rose-200 text-rose-800',
        sentences: [
            { en: "I have a problem.", th: "ฉันมีปัญหา" }, { en: "I have a headache.", th: "ฉันปวดหัว" }, { en: "I have a cold.", th: "ฉันเป็นหวัด" }, { en: "I’m lost.", th: "ฉันหลงทาง" }, { en: "I’m confused.", th: "ฉันงง / สับสน" }, { en: "I’m so stressed.", th: "ฉันเครียดมาก" }, { en: "It doesn't work.", th: "มันใช้งานไม่ได้" }, { en: "It’s broken.", th: "มันพัง / แตก" }, { en: "It’s too loud.", th: "เสียงดังเกินไป" }, { en: "It’s too cold in here.", th: "ในนี้หนาวเกินไป" }, { en: "It’s too expensive.", th: "มันแพงเกินไป" }, { en: "It’s really annoying.", th: "มันน่ารำคาญจริงๆ" }, { en: "There is a mistake.", th: "มีความผิดพลาดเกิดขึ้น" }, { en: "There is no internet.", th: "เน็ตใช้ไม่ได้ / ไม่มีเน็ต" }, { en: "The traffic is terrible.", th: "การจราจรแย่มาก (รถติด)" }, { en: "This is not what I ordered.", th: "นี่ไม่ใช่ที่ฉันสั่งไป" }, { en: "This is taking too long.", th: "นี่มันใช้เวลานานเกินไปแล้ว" }, { en: "Something is wrong.", th: "มีบางอย่างผิดปกติ" }, { en: "I don't have enough money.", th: "ฉันมีเงินไม่พอ" }, { en: "I don't have time.", th: "ฉันไม่มีเวลา" }, { en: "I can't find my wallet.", th: "ฉันหากระเป๋าตังค์ไม่เจอ" }, { en: "I'm running late.", th: "ฉันกำลังจะไปสายแล้ว" }
        ]
    },
    {
        id: 'K', title: 'K. Reactions & Exclamations', color: 'bg-amber-100 border-amber-200 text-amber-800',
        sentences: [
            { en: "That’s great!", th: "ยอดเยี่ยมไปเลย!" }, { en: "That’s good news.", th: "ข่าวดีเลยนะนั่น" }, { en: "That’s awesome.", th: "เจ๋งไปเลย" }, { en: "That’s interesting.", th: "น่าสนใจแฮะ" }, { en: "That’s nice.", th: "ดีจังเลย" }, { en: "That’s funny.", th: "ตลกจัง" }, { en: "That’s weird.", th: "แปลกจัง" }, { en: "That’s too bad.", th: "แย่จังเลย" }, { en: "That’s terrible.", th: "เลวร้ายมาก" }, { en: "That’s crazy.", th: "บ้าไปแล้ว" }, { en: "That’s impossible.", th: "เป็นไปไม่ได้น่า" }, { en: "That’s right.", th: "ถูกต้องเลย" }, { en: "That’s wrong.", th: "ผิดแล้วล่ะ" }, { en: "That’s enough.", th: "พอได้แล้ว" }, { en: "No way!", th: "ไม่มีทาง! / ไม่จริงน่า!" }, { en: "Oh my god.", th: "คุณพระช่วย / พระเจ้าช่วย" }, { en: "Are you serious?", th: "พูดจริงดิ? / เอาจริงเหรอ?" }, { en: "Are you kidding me?", th: "ล้อเล่นป่ะเนี่ย?" }, { en: "Really?", th: "จริงเหรอ?" }, { en: "Exactly!", th: "เป๊ะเลย / ใช่เลย!" }, { en: "Absolutely!", th: "แน่นอนที่สุด / ชัวร์ป้าบ" }, { en: "Definitely.", th: "แน่นอน" }, { en: "Sounds good.", th: "ฟังดูดีนะ" }, { en: "Sounds like a plan.", th: "เอาตามแผนนี้เลย (ตกลง)" }, { en: "Good luck!", th: "โชคดีนะ!" }, { en: "Take care.", th: "ดูแลตัวเองนะ" }, { en: "Don't worry.", th: "ไม่ต้องกังวลนะ" }, { en: "Never mind.", th: "ช่างมันเถอะ / ไม่เป็นไร" }
        ]
    },
    {
        id: 'L', title: 'L. University Life, Technology & AI', color: 'bg-sky-100 border-sky-200 text-sky-800',
        sentences: [
            { en: "I’m a student.", th: "ฉันเป็นนักเรียน/นักศึกษา" }, { en: "I go to university.", th: "ฉันเรียนมหาวิทยาลัย" }, { en: "I have a class now.", th: "ตอนนี้มีเรียน" }, { en: "I have an exam tomorrow.", th: "พรุ่งนี้ฉันมีสอบ" }, { en: "The lecture is boring.", th: "บรรยาย/เลคเชอร์น่าเบื่อมาก" }, { en: "The professor is strict.", th: "อาจารย์ดุ/เข้มงวดมาก" }, { en: "Where is the library?", th: "ห้องสมุดอยู่ที่ไหน?" }, { en: "Is the library open?", th: "ห้องสมุดเปิดอยู่ไหม?" }, { en: "I need to print this.", th: "ฉันต้องปรินต์อันนี้" }, { en: "I use my laptop every day.", th: "ฉันใช้แล็ปท็อปทุกวัน" }, { en: "I use social media a lot.", th: "ฉันเล่นโซเชียลบ่อยมาก" }, { en: "I don't use Facebook.", th: "ฉันไม่เล่นเฟซบุ๊ก" }, { en: "Do you use Instagram?", th: "คุณเล่นไอจีไหม?" }, { en: "Do you use ChatGPT?", th: "คุณใช้ ChatGPT ไหม?" }, { en: "I use AI for my homework.", th: "ฉันใช้ AI ช่วยทำการบ้าน" }, { en: "It helps me write emails.", th: "มันช่วยฉันเขียนอีเมล" }, { en: "It translates text quickly.", th: "มันแปลข้อความได้เร็วมาก" }, { en: "The app keeps crashing.", th: "แอปมันเด้งหลุดตลอดเลย" }, { en: "I need to update my phone.", th: "ฉันต้องอัปเดตมือถือ" }, { en: "I need to charge my laptop.", th: "ฉันต้องชาร์จแบตแล็ปท็อป" }, { en: "Do you have a charger?", th: "มีที่ชาร์จไหม?" }, { en: "Is there Wi-Fi here?", th: "ที่นี่มีไวไฟไหม?" }, { en: "What is the Wi-Fi password?", th: "รหัสไวไฟคืออะไร?" }, { en: "I’m playing video games.", th: "ฉันกำลังเล่นเกม" }, { en: "I’m watching a stream.", th: "ฉันกำลังดูไลฟ์สตรีม" }, { en: "I’m scrolling through TikTok.", th: "ฉันกำลังไถ TikTok อยู่" }
        ]
    },
    {
        id: 'M', title: 'M. Bonus Series: "I am" & "It is"', color: 'bg-fuchsia-100 border-fuchsia-200 text-fuchsia-800',
        sentences: [
            { en: "I’m hungry.", th: "ฉันหิว" }, { en: "I’m thirsty.", th: "ฉันกระหายน้ำ/หิวน้ำ" }, { en: "I’m full.", th: "ฉันอิ่มแล้ว" }, { en: "I’m nervous.", th: "ฉันประหม่า / ตื่นเต้น(กลัว)" }, { en: "I’m excited.", th: "ฉันตื่นเต้น (ดีใจ)" }, { en: "I’m bored.", th: "ฉันเบื่อ" }, { en: "I’m ready.", th: "ฉันพร้อมแล้ว" }, { en: "I’m sure.", th: "ฉันมั่นใจ" }, { en: "I’m not sure.", th: "ฉันไม่แน่ใจ" }, { en: "It’s sunny today.", th: "วันนี้แดดจ้า" }, { en: "It’s raining right now.", th: "ตอนนี้ฝนตกอยู่" }, { en: "It’s windy outside.", th: "ข้างนอกลมแรง" }, { en: "It’s getting dark.", th: "เริ่มมืดแล้ว" }, { en: "It’s getting late.", th: "เริ่มดึกแล้ว / สายแล้ว" }, { en: "It’s almost time.", th: "เกือบถึงเวลาแล้ว" }
        ]
    }
];

// ดันข้อมูลลงในตัวแปรหลัก
window.ESB_Sessions.push({
    id: 'session-1',
    title: 'Session 1: Basic Conversations',
    data: Part1Data,
    defaultOpen: true
});