// ข้อมูลหมวดหมู่ของ Session 2.1 — Grammar Gaps
const Part21Data = [
    {
        id: 'A21', title: 'A. Passive Voice', color: 'bg-slate-50 border-slate-200 text-slate-900',
        sentences: [
            { en: "The report is sent to the manager every Monday.", th: "รายงานถูกส่งให้ผู้จัดการทุกวันจันทร์" },
            { en: "English is spoken all over the world.", th: "ภาษาอังกฤษถูกพูดกันทั่วโลก" },
            { en: "The office is cleaned every night.", th: "ออฟฟิศถูกทำความสะอาดทุกคืน" },
            { en: "This product is sold online only.", th: "สินค้าชิ้นนี้จำหน่ายเฉพาะออนไลน์" },
            { en: "The results are announced every Friday.", th: "ผลจะถูกประกาศทุกวันศุกร์" },
            { en: "The meeting was cancelled at the last minute.", th: "การประชุมถูกยกเลิกในนาทีสุดท้าย" },
            { en: "My wallet was stolen on the bus.", th: "กระเป๋าตังค์ฉันถูกขโมยบนรถเมล์" },
            { en: "The email was sent to the wrong person.", th: "อีเมลถูกส่งไปหาคนผิด" },
            { en: "The project was finished ahead of schedule.", th: "โปรเจกต์เสร็จก่อนกำหนดเลย" },
            { en: "We were told to wait outside.", th: "เราถูกบอกให้ไปรอข้างนอก" },
            { en: "The file was deleted by mistake.", th: "ไฟล์ถูกลบโดยไม่ได้ตั้งใจ" },
            { en: "She was offered a job in Singapore.", th: "เธอได้รับข้อเสนองานในสิงคโปร์" },
            { en: "The issue has been resolved.", th: "ปัญหาได้รับการแก้ไขแล้ว" },
            { en: "All the tickets have been sold out.", th: "ตั๋วทั้งหมดขายหมดแล้ว" },
            { en: "The package has been delivered.", th: "พัสดุถูกส่งถึงแล้ว" },
            { en: "The deadline has been moved to next week.", th: "ดีดไลน์ถูกเลื่อนไปอาทิตย์หน้าแล้ว" },
            { en: "The app has been updated to the latest version.", th: "แอปได้รับการอัปเดตเป็นเวอร์ชันล่าสุดแล้ว" },
            { en: "I haven't been told anything about this.", th: "ฉันไม่ได้รับแจ้งเรื่องนี้เลยสักนิด" },
            { en: "The results will be announced next week.", th: "ผลจะถูกประกาศสัปดาห์หน้า" },
            { en: "All employees will be given a bonus.", th: "พนักงานทุกคนจะได้รับโบนัส" },
            { en: "The building will be demolished next year.", th: "อาคารจะถูกรื้อถอนปีหน้า" },
            { en: "This must be done before Friday.", th: "เรื่องนี้ต้องเสร็จก่อนวันศุกร์" },
            { en: "Mistakes should be reported immediately.", th: "ข้อผิดพลาดควรรายงานทันที" },
            { en: "This room can be booked online.", th: "ห้องนี้สามารถจองออนไลน์ได้เลย" },
            { en: "The form needs to be filled in completely.", th: "ฟอร์มต้องกรอกให้ครบทุกช่อง" },
            { en: "This information might be used later.", th: "ข้อมูลนี้อาจถูกนำไปใช้ภายหลัง" },
            { en: "Was the report submitted on time?", th: "รายงานถูกส่งตรงเวลาไหม?" },
            { en: "When was this photo taken?", th: "รูปนี้ถ่ายเมื่อไหร่?" },
            { en: "Has the problem been fixed yet?", th: "ปัญหานั้นได้รับการแก้ไขหรือยัง?" },
            { en: "Where is the meeting being held?", th: "การประชุมจัดที่ไหน?" },
        ]
    },
    {
        id: 'B21', title: 'B. Reported Speech', color: 'bg-violet-50 border-violet-200 text-violet-900',
        sentences: [
            { en: "She said she was tired.", th: "เธอบอกว่าเธอเหนื่อย" },
            { en: "He said he would call me later.", th: "เขาบอกว่าจะโทรหาฉันทีหลัง" },
            { en: "They said they had already eaten.", th: "พวกเขาบอกว่ากินข้าวไปแล้ว" },
            { en: "She said she didn't understand the question.", th: "เธอบอกว่าไม่เข้าใจคำถาม" },
            { en: "He said he was working from home that day.", th: "เขาบอกว่าวันนั้นทำงานอยู่ที่บ้าน" },
            { en: "She said she had never been to Japan.", th: "เธอบอกว่าไม่เคยไปญี่ปุ่นเลย" },
            { en: "He said the meeting had been cancelled.", th: "เขาบอกว่าการประชุมถูกยกเลิกแล้ว" },
            { en: "She said she would finish the report by Monday.", th: "เธอบอกว่าจะทำรายงานเสร็จภายในวันจันทร์" },
            { en: "They said they couldn't come to the party.", th: "พวกเขาบอกว่าไม่ได้มางานปาร์ตี้" },
            { en: "He said he might be late.", th: "เขาบอกว่าอาจจะมาสาย" },
            { en: "The doctor told me to get more rest.", th: "หมอบอกให้ฉันพักผ่อนให้มากขึ้น" },
            { en: "My boss told me to send the report immediately.", th: "หัวหน้าบอกให้ฉันส่งรายงานทันที" },
            { en: "She told me not to worry about it.", th: "เธอบอกให้ฉันไม่ต้องกังวล" },
            { en: "The teacher told us to submit our work by Friday.", th: "อาจารย์บอกให้เราส่งงานภายในวันศุกร์" },
            { en: "He told her to take a deep breath.", th: "เขาบอกให้เธอหายใจลึกๆ" },
            { en: "They told me not to open the door.", th: "พวกเขาบอกให้ฉันอย่าเปิดประตู" },
            { en: "She asked if I was free on Saturday.", th: "เธอถามว่าวันเสาร์ฉันว่างไหม" },
            { en: "He asked whether I had seen the email.", th: "เขาถามว่าฉันเห็นอีเมลนั้นหรือยัง" },
            { en: "They asked if we wanted to join them.", th: "พวกเขาถามว่าเราอยากไปด้วยกันไหม" },
            { en: "She asked me if I knew the answer.", th: "เธอถามว่าฉันรู้คำตอบไหม" },
            { en: "He asked whether the shop was still open.", th: "เขาถามว่าร้านยังเปิดอยู่ไหม" },
            { en: "She asked me where I had been.", th: "เธอถามว่าฉันไปไหนมา" },
            { en: "He asked what time the flight arrived.", th: "เขาถามว่าเที่ยวบินถึงกี่โมง" },
            { en: "They asked why I was late.", th: "พวกเขาถามว่าทำไมฉันถึงมาสาย" },
            { en: "She asked how much it cost.", th: "เธอถามว่ามันราคาเท่าไหร่" },
            { en: "He asked which bus I took.", th: "เขาถามว่าฉันนั่งรถสายไหน" },
            { en: "My friend told me that the food there was amazing.", th: "เพื่อนบอกว่าอาหารที่นั่นอร่อยมาก" },
            { en: "She said she had been waiting for over an hour.", th: "เธอบอกว่ารอมาเกินชั่วโมงแล้ว" },
            { en: "He told me he had already paid the bill.", th: "เขาบอกว่าจ่ายบิลไปแล้ว" },
            { en: "They asked me if I could help them move.", th: "พวกเขาถามว่าฉันช่วยขนของได้ไหม" },
        ]
    },
    {
        id: 'C21', title: 'C. Present Perfect Continuous', color: 'bg-teal-50 border-teal-200 text-teal-900',
        sentences: [
            { en: "I've been waiting for you for 20 minutes.", th: "ฉันรอคุณมา 20 นาทีแล้วนะ" },
            { en: "She's been studying English for two years.", th: "เธอเรียนภาษาอังกฤษมาสองปีแล้ว" },
            { en: "He's been working on this project all week.", th: "เขาทำโปรเจกต์นี้มาทั้งอาทิตย์เลย" },
            { en: "I've been feeling really tired lately.", th: "ช่วงนี้ฉันรู้สึกเหนื่อยตลอดเลย" },
            { en: "They've been arguing since this morning.", th: "พวกเขาทะเลาะกันมาตั้งแต่เช้าแล้ว" },
            { en: "I've been trying to call you all day.", th: "ฉันโทรหาคุณมาทั้งวันเลยนะ" },
            { en: "She's been living in Bangkok for three years.", th: "เธออาศัยอยู่ในกรุงเทพมาสามปีแล้ว" },
            { en: "It's been raining since last night.", th: "ฝนตกมาตั้งแต่เมื่อคืนเลย" },
            { en: "How long have you been learning Thai?", th: "คุณเรียนภาษาไทยมานานแค่ไหนแล้ว?" },
            { en: "I've been thinking about changing jobs.", th: "ฉันคิดเรื่องเปลี่ยนงานอยู่เลยช่วงนี้" },
            { en: "He's been going to the gym every day.", th: "เขาไปยิมทุกวันมาสักพักแล้ว" },
            { en: "We've been looking for a new apartment.", th: "เรากำลังหาอพาร์ตเมนต์ใหม่กันอยู่" },
            { en: "I haven't been sleeping well recently.", th: "ช่วงนี้ฉันนอนไม่ค่อยหลับเลย" },
            { en: "She hasn't been feeling well since Monday.", th: "เธอรู้สึกไม่สบายมาตั้งแต่วันจันทร์เลย" },
            { en: "They've been working together for five years.", th: "พวกเขาทำงานร่วมกันมาห้าปีแล้ว" },
            { en: "I've been saving money to buy a new laptop.", th: "ฉันเก็บเงินซื้อแล็ปท็อปใหม่อยู่" },
            { en: "What have you been up to lately?", th: "ช่วงนี้ทำอะไรบ้างเหรอ?" },
            { en: "I've been reading a really interesting book.", th: "ฉันกำลังอ่านหนังสือที่น่าสนใจมากอยู่" },
            { en: "He's been complaining about the same thing for weeks.", th: "เขาบ่นเรื่องเดิมมาหลายอาทิตย์แล้ว" },
            { en: "I've been meaning to call you for ages.", th: "ฉันตั้งใจจะโทรหาคุณมาสักพักแล้ว แต่ยังไม่ได้โทรซักที" },
        ]
    },
    {
        id: 'D21', title: 'D. Past Perfect (had done)', color: 'bg-rose-50 border-rose-200 text-rose-900',
        sentences: [
            { en: "By the time I arrived, the movie had already started.", th: "กว่าฉันจะไปถึง หนังก็เริ่มไปแล้ว" },
            { en: "She had already left when I called.", th: "เธอกลับไปแล้วตอนที่ฉันโทรหา" },
            { en: "I had never eaten sushi before I went to Japan.", th: "ก่อนไปญี่ปุ่น ฉันไม่เคยกินซูชิมาก่อนเลย" },
            { en: "He had finished all his work before the deadline.", th: "เขาทำงานทั้งหมดเสร็จก่อนกำหนดเลย" },
            { en: "I was exhausted because I hadn't slept the night before.", th: "ฉันเหนื่อยมากเพราะไม่ได้นอนมาคืนก่อน" },
            { en: "They had been waiting for two hours when he finally arrived.", th: "พวกเขารอมาสองชั่วโมงกว่าเขาจะมาถึง" },
            { en: "I realized I had left my keys at home.", th: "ฉันนึกขึ้นได้ว่าลืมกุญแจทิ้งไว้ที่บ้าน" },
            { en: "She had never driven on the highway before.", th: "เธอไม่เคยขับรถบนทางด่วนมาก่อนเลย" },
            { en: "By the time we got there, they had sold out.", th: "กว่าเราจะไปถึง สินค้าก็หมดไปแล้ว" },
            { en: "I hadn't heard the news until you told me.", th: "ฉันไม่รู้ข่าวนั้นเลยจนกว่าคุณจะบอก" },
            { en: "He had studied hard for the exam but still failed.", th: "เขาอ่านหนังสือหนักมาก แต่ก็ยังสอบตก" },
            { en: "I had just finished eating when they arrived.", th: "ฉันเพิ่งกินข้าวเสร็จตอนที่พวกเขามาถึง" },
            { en: "She was upset because someone had taken her seat.", th: "เธอหัวร้อนเพราะมีคนมานั่งที่ของเธอ" },
            { en: "I knew I had made a mistake.", th: "ฉันรู้ว่าตัวเองทำพลาดไปแล้ว" },
            { en: "The restaurant had closed by the time we arrived.", th: "ร้านอาหารปิดไปแล้วกว่าพวกเราจะถึง" },
            { en: "He said he had already seen that movie twice.", th: "เขาบอกว่าดูหนังเรื่องนั้นไปสองรอบแล้ว" },
            { en: "I had forgotten to save the file before the computer crashed.", th: "ฉันลืมเซฟไฟล์ก่อนคอมจะแฮงค์" },
            { en: "She felt relieved because she had passed the test.", th: "เธอรู้สึกโล่งอกเพราะสอบผ่านแล้ว" },
            { en: "Had you ever been to Thailand before last year?", th: "ก่อนปีที่แล้วคุณเคยมาเที่ยวไทยไหม?" },
            { en: "I wished I had taken the other road.", th: "ฉันเสียดายที่ไม่ได้ไปอีกเส้นทางนึง" },
        ]
    },
    {
        id: 'E21', title: 'E. Phrasal Verbs (Essential Set)', color: 'bg-amber-50 border-amber-200 text-amber-900',
        sentences: [
            { en: "I gave up trying to fix it myself.", th: "ฉันยอมแพ้แล้ว เลิกซ่อมด้วยตัวเองดีกว่า" },
            { en: "Don't give up — you're almost there.", th: "อย่ายอมแพ้นะ ใกล้ถึงแล้ว" },
            { en: "I found out that the event was cancelled.", th: "ฉันมารู้ทีหลังว่างานถูกยกเลิก" },
            { en: "How did you find out about this place?", th: "คุณรู้จักที่นี่ได้ยังไง?" },
            { en: "I can't figure out how to use this app.", th: "ฉันหาไม่เจอเลยว่าต้องใช้แอปนี้ยังไง" },
            { en: "Let me figure out the best route first.", th: "ให้ฉันหาเส้นทางที่ดีที่สุดก่อนนะ" },
            { en: "I keep putting off going to the dentist.", th: "ฉันเลื่อนการไปหาหมอฟันมาตลอดเลย" },
            { en: "The meeting was put off until next week.", th: "การประชุมถูกเลื่อนออกไปอาทิตย์หน้า" },
            { en: "We ran out of coffee this morning.", th: "เช้านี้กาแฟหมดพอดีเลย" },
            { en: "I'm running out of time.", th: "ฉันกำลังจะหมดเวลาแล้ว" },
            { en: "Let me look up the word for you.", th: "ให้ฉันค้นความหมายของคำนั้นให้หน่อย" },
            { en: "I looked up the address online.", th: "ฉันค้นที่อยู่ออนไลน์ไว้แล้ว" },
            { en: "Can you turn off the lights when you leave?", th: "ช่วยปิดไฟก่อนออกไปด้วยได้ไหม?" },
            { en: "Turn on the fan — it's so hot in here.", th: "เปิดพัดลมหน่อยนะ ในนี้ร้อนมาก" },
            { en: "Can you pick me up at the airport?", th: "มารับฉันที่สนามบินได้ไหม?" },
            { en: "I picked up some snacks on the way home.", th: "ฉันแวะซื้อขนมมาฝากตอนกลับบ้าน" },
            { en: "Carry on — don't let me interrupt you.", th: "ทำต่อไปเลยนะ ไม่ต้องหยุดเพราะฉัน" },
            { en: "We carried on working despite the noise.", th: "เราทำงานต่อไปแม้จะมีเสียงดัง" },
            { en: "I need to get rid of these old clothes.", th: "ฉันต้องจัดการเสื้อผ้าเก่าๆ พวกนี้ซักที" },
            { en: "How do I get rid of this virus on my computer?", th: "จะจัดการไวรัสในคอมตัวนี้ยังไงดี?" },
            { en: "She brought up an interesting point in the meeting.", th: "เธอหยิบยกประเด็นที่น่าสนใจขึ้นมาในที่ประชุม" },
            { en: "Don't bring up that topic — it's sensitive.", th: "อย่าพูดเรื่องนั้นนะ มันเป็นเรื่องอ่อนไหว" },
            { en: "Can you come up with a better idea?", th: "คุณคิดไอเดียที่ดีกว่านี้ออกไหม?" },
            { en: "I couldn't come up with an excuse in time.", th: "ฉันคิดข้ออ้างไม่ทันเลย" },
            { en: "Can you help me set up this new phone?", th: "ช่วยฉันตั้งค่ามือถือเครื่องใหม่หน่อยได้ไหม?" },
            { en: "We need to set up a meeting with the team.", th: "เราต้องนัดประชุมกับทีมก่อน" },
            { en: "I went through a really difficult time last year.", th: "ปีที่แล้วฉันผ่านช่วงเวลาที่ยากมากมาได้" },
            { en: "Let me go through the plan one more time.", th: "ให้ฉันทบทวนแผนอีกสักรอบนะ" },
            { en: "I'm looking forward to the holidays.", th: "ฉันตั้งตารอวันหยุดมากเลย" },
            { en: "We should catch up sometime soon.", th: "เราควรหาเวลานั่งคุยกันบ้างนะ" },
        ]
    },
    {
        id: 'F21', title: 'F. Causative — have/get something done', color: 'bg-cyan-50 border-cyan-200 text-cyan-900',
        sentences: [
            { en: "I need to get my hair cut.", th: "ฉันต้องไปตัดผมซักที" },
            { en: "She had her car repaired at the garage.", th: "เธอเอารถไปซ่อมที่อู่" },
            { en: "I'm going to get my phone screen fixed.", th: "ฉันจะเอาจอมือถือไปซ่อม" },
            { en: "We had the air conditioner serviced last month.", th: "เดือนที่แล้วเราเรียกช่างมาเช็คแอร์" },
            { en: "I need to get my eyes checked.", th: "ฉันต้องไปตรวจสายตาซักที" },
            { en: "She got her dress altered before the party.", th: "เธอเอาชุดไปแก้ก่อนงานปาร์ตี้" },
            { en: "I had my laptop cleaned by a technician.", th: "ฉันให้ช่างทำความสะอาดแล็ปท็อปให้" },
            { en: "We're getting the apartment repainted next month.", th: "เดือนหน้าเราจะให้เขาทาสีอพาร์ตเมนต์ใหม่" },
            { en: "I got my documents translated professionally.", th: "ฉันให้มืออาชีพแปลเอกสารให้" },
            { en: "She had her photo taken by a professional photographer.", th: "เธอให้ช่างภาพมืออาชีพถ่ายรูปให้" },
            { en: "You should get that mole checked by a doctor.", th: "คุณควรให้หมอตรวจไฝนั้นนะ" },
            { en: "He got his passport renewed last week.", th: "อาทิตย์ที่แล้วเขาต่ออายุพาสปอร์ต" },
            { en: "I need to have this package delivered by tomorrow.", th: "ฉันต้องให้ส่งพัสดุนี้ถึงภายในพรุ่งนี้" },
            { en: "She had her nails done before the interview.", th: "เธอไปทำเล็บก่อนสัมภาษณ์งาน" },
            { en: "We had our house cleaned before the guests arrived.", th: "เราให้คนมาทำความสะอาดบ้านก่อนแขกมา" },
        ]
    },
    {
        id: 'G21', title: 'G. Wish / If Only / Would Rather', color: 'bg-purple-50 border-purple-200 text-purple-900',
        sentences: [
            { en: "I wish I had more time to travel.", th: "ฉันอยากมีเวลาเที่ยวให้มากกว่านี้จัง" },
            { en: "I wish I spoke English more fluently.", th: "ฉันอยากพูดภาษาอังกฤษให้คล่องกว่านี้จัง" },
            { en: "She wishes she lived closer to her family.", th: "เธออยากอยู่ใกล้ครอบครัวมากกว่านี้" },
            { en: "I wish it wasn't so hot today.", th: "อยากให้วันนี้มันไม่ร้อนขนาดนี้จัง" },
            { en: "He wishes he knew how to cook properly.", th: "เขาอยากทำอาหารเป็นจัง" },
            { en: "I wish I had studied harder for the exam.", th: "รู้งี้น่าจะตั้งใจอ่านหนังสือมากกว่านี้" },
            { en: "I wish I hadn't said that.", th: "ฉันเสียใจที่พูดเรื่องนั้นออกไป" },
            { en: "She wishes she had taken the other job offer.", th: "เธอเสียดายที่ไม่ได้รับงานที่อีกที่นั้น" },
            { en: "I wish I had saved more money last year.", th: "รู้งี้น่าจะเก็บเงินให้มากกว่านี้ตั้งแต่ปีที่แล้ว" },
            { en: "He wishes he hadn't left his hometown.", th: "เขาเสียดายที่ออกจากบ้านเกิด" },
            { en: "I'd rather stay home tonight.", th: "คืนนี้ฉันอยากอยู่บ้านมากกว่า" },
            { en: "I'd rather take the train than drive.", th: "ฉันอยากนั่งรถไฟมากกว่าขับรถเอง" },
            { en: "She'd rather not talk about it right now.", th: "ตอนนี้เธออยากจะยังไม่พูดเรื่องนั้นมากกว่า" },
            { en: "I'd rather have coffee than tea, thanks.", th: "ขอกาแฟมากกว่าชานะ ขอบใจ" },
            { en: "I'd rather you didn't tell anyone about this.", th: "ฉันอยากให้คุณไม่บอกเรื่องนี้กับใคร" },
            { en: "I'd rather you came earlier next time.", th: "ฉันอยากให้คุณมาเร็วกว่านี้คราวหน้า" },
            { en: "She'd rather we met somewhere quiet.", th: "เธออยากให้เราไปนัดกันที่เงียบๆ มากกว่า" },
            { en: "If only I had more energy right now.", th: "ถ้าตอนนี้ฉันมีพลังงานมากกว่านี้ก็ดีจัง" },
            { en: "If only I had listened to your advice.", th: "รู้งี้น่าจะฟังคำแนะนำของคุณตั้งแต่แรก" },
            { en: "If only it wasn't raining right now.", th: "ถ้าตอนนี้ฝนไม่ตกก็ดีนะ" },
        ]
    },
    {
        id: 'H21', title: 'H. Modal Verbs — Deduction & Past Speculation', color: 'bg-sky-50 border-sky-200 text-sky-900',
        sentences: [
            { en: "You must be tired after such a long journey.", th: "คุณต้องเหนื่อยมากแน่ๆ หลังเดินทางมาไกลขนาดนั้น" },
            { en: "She must have forgotten about the meeting.", th: "เธอคงลืมเรื่องประชุมไป" },
            { en: "He must have worked really hard to pass.", th: "เขาคงอุตส่าห์เรียนหนักมากถึงสอบผ่านได้" },
            { en: "They must have left already.", th: "พวกเขาคงออกไปแล้วแน่ๆ" },
            { en: "That must have been really embarrassing for you.", th: "นั่นคงอายมากเลยนะ" },
            { en: "She can't have finished already — it's too fast.", th: "เธอทำไม่มีทางเสร็จแล้วหรอก เร็วเกินไปมากเลย" },
            { en: "He can't have known about this beforehand.", th: "เขาไม่มีทางรู้เรื่องนี้มาก่อนหน้านี้แน่ๆ" },
            { en: "That can't have been easy for her at all.", th: "นั่นคงไม่ง่ายสำหรับเธอเลยแม้แต่น้อย" },
            { en: "She might have missed the bus.", th: "เธออาจจะตกรถเมล์ก็ได้" },
            { en: "He could have told me earlier, but he didn't.", th: "เขาน่าจะบอกฉันแต่เนิ่นๆ แต่ก็ไม่ได้บอก" },
            { en: "I might have left it at the office.", th: "ฉันอาจจะทิ้งมันไว้ที่ออฟฟิศก็ได้" },
            { en: "They might not have received the email.", th: "พวกเขาอาจจะยังไม่ได้รับอีเมลก็ได้" },
            { en: "I should have called ahead before going.", th: "รู้งี้น่าจะโทรถามก่อนไปเนอะ" },
            { en: "You should have told me sooner.", th: "คุณควรบอกฉันให้เร็วกว่านี้นะ" },
            { en: "She should have been more careful.", th: "เธอน่าจะระวังให้มากกว่านี้" },
            { en: "I shouldn't have eaten so much last night.", th: "เมื่อคืนไม่น่ากินเยอะขนาดนั้นเลย" },
            { en: "We should have left earlier to avoid traffic.", th: "รู้งี้ออกเดินทางก่อนก็ไม่ต้องติดรถแล้ว" },
            { en: "You needn't have worried — everything was fine.", th: "ไม่ต้องกังวลขนาดนั้นก็ได้นะ ทุกอย่างเรียบร้อยดี" },
            { en: "She needn't have cooked so much food for us.", th: "เธอไม่ต้องทำอาหารเยอะขนาดนั้นสำหรับพวกเราก็ได้" },
            { en: "He must be at least 40 years old.", th: "เขาต้องอายุอย่างน้อย 40 ปีแน่ๆ" },
            { en: "That could be the reason why she's upset.", th: "นั่นอาจจะเป็นสาเหตุที่เธอหัวร้อนก็ได้" },
            { en: "She may not have understood the instructions.", th: "เธออาจจะไม่เข้าใจคำแนะนำก็ได้" },
            { en: "They might have been stuck in traffic.", th: "พวกเขาอาจจะติดรถอยู่ก็ได้" },
            { en: "He should have known better than that.", th: "เขาน่าจะรู้ดีกว่านั้นนะ" },
            { en: "You couldn't have come at a better time.", th: "คุณมาถูกเวลามากเลยนะ" },
        ]
    },
    {
        id: 'I21', title: 'I. So / Such / Too / Enough', color: 'bg-lime-50 border-lime-200 text-lime-900',
        sentences: [
            { en: "The weather is so nice today.", th: "วันนี้อากาศดีจริงๆ เลย" },
            { en: "She speaks English so naturally.", th: "เธอพูดภาษาอังกฤษได้ธรรมชาติมากเลย" },
            { en: "He was so tired that he fell asleep immediately.", th: "เขาเหนื่อยมากจนหลับทันทีเลย" },
            { en: "It was so cold that we decided to stay inside.", th: "มันหนาวมากจนเราตัดสินใจอยู่ข้างใน" },
            { en: "She's so kind — she always helps everyone.", th: "เธอใจดีมากเลย คอยช่วยทุกคนเสมอ" },
            { en: "It was such a great movie.", th: "หนังเรื่องนั้นดีมากจริงๆ" },
            { en: "He's such a hardworking person.", th: "เขาเป็นคนขยันมากๆ เลย" },
            { en: "It was such a long day that I just wanted to sleep.", th: "วันนี้ยาวนานมากจนอยากนอนอย่างเดียวเลย" },
            { en: "She had such a good time at the party.", th: "เธอสนุกกับงานปาร์ตี้มากเลย" },
            { en: "It was such beautiful weather that we went for a walk.", th: "อากาศดีมากจนเราออกไปเดินเล่น" },
            { en: "This bag is too heavy to carry.", th: "กระเป๋าใบนี้หนักเกินไปจะถือไหว" },
            { en: "It's too late to cancel now.", th: "สายเกินไปแล้วที่จะยกเลิก" },
            { en: "He speaks too fast for me to follow.", th: "เขาพูดเร็วเกินไปจนฉันตามไม่ทัน" },
            { en: "The room is too small for all of us.", th: "ห้องเล็กเกินสำหรับพวกเราทุกคน" },
            { en: "Are you sure you have enough time?", th: "แน่ใจนะว่ามีเวลาพอ?" },
            { en: "She's old enough to make her own decisions.", th: "เธอโตพอที่จะตัดสินใจเองได้แล้ว" },
            { en: "He didn't study hard enough to pass.", th: "เขาขยันอ่านหนังสือไม่พอที่จะผ่านได้" },
            { en: "Is the signal strong enough to make a video call?", th: "สัญญาณแรงพอจะวิดีโอคอลได้ไหม?" },
            { en: "I haven't saved enough money yet.", th: "ฉันยังเก็บเงินได้ไม่พอเลย" },
            { en: "She was confident enough to speak in front of the class.", th: "เธอมั่นใจพอที่จะพูดต่อหน้าชั้นเรียนได้" },
        ]
    },
    {
        id: 'J21', title: 'J. Tag Questions & Indirect Questions (Extended)', color: 'bg-pink-50 border-pink-200 text-pink-900',
        sentences: [
            { en: "It's a bit cold today, isn't it?", th: "วันนี้หนาวนิดหน่อยนะ ว่าไหม?" },
            { en: "You've been here before, haven't you?", th: "คุณเคยมาที่นี่แล้วใช่ไหม?" },
            { en: "She can't drive, can she?", th: "เธอขับรถไม่เป็นใช่ไหม?" },
            { en: "The meeting starts at 10, doesn't it?", th: "ประชุมเริ่ม 10 โมงใช่ไหม?" },
            { en: "You haven't told anyone, have you?", th: "คุณไม่ได้บอกใครนะ ใช่ไหม?" },
            { en: "Nothing went wrong, did it?", th: "ไม่มีอะไรผิดพลาดนะ ใช่ไหม?" },
            { en: "Let's take a break, shall we?", th: "หยุดพักกันแป๊บนึงได้ไหม?" },
            { en: "Could you tell me where I can find the nearest ATM?", th: "ช่วยบอกหน่อยได้ไหมว่าตู้ ATM ที่ใกล้ที่สุดอยู่ที่ไหน?" },
            { en: "Do you have any idea how long it will take?", th: "พอจะรู้ไหมว่ามันจะใช้เวลานานแค่ไหน?" },
            { en: "I was wondering if you could give me some advice.", th: "ฉันอยากรู้ว่าคุณพอจะให้คำแนะนำฉันได้ไหม" },
            { en: "Can you tell me what the problem is exactly?", th: "ช่วยบอกหน่อยได้ไหมว่าปัญหาที่แท้จริงคืออะไร?" },
            { en: "Do you know if the office is open on weekends?", th: "คุณรู้ไหมว่าออฟฟิศเปิดช่วงสุดสัปดาห์ไหม?" },
            { en: "I'd like to know whether this is the right form.", th: "ฉันอยากทราบว่านี่คือฟอร์มที่ถูกต้องไหม" },
            { en: "Could you explain how this process works?", th: "ช่วยอธิบายหน่อยได้ไหมว่ากระบวนการนี้ทำงานยังไง?" },
            { en: "I'm not quite sure what time the next bus is.", th: "ฉันไม่แน่ใจเลยว่ารถเที่ยวถัดไปมากี่โมง" },
        ]
    },
    {
        id: 'K21', title: 'K. Advanced Linking Words', color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
        sentences: [
            { en: "Nevertheless, we decided to continue with the plan.", th: "อย่างไรก็ตาม เราตัดสินใจดำเนินแผนต่อไป" },
            { en: "The weather was terrible; nevertheless, we had a great time.", th: "อากาศแย่มาก แต่อย่างไรก็ตาม เราก็สนุกกันดี" },
            { en: "Whereas I prefer coffee, my sister loves tea.", th: "ในขณะที่ฉันชอบกาแฟ น้องสาวกลับชอบชา" },
            { en: "Whereas city life is exciting, it can also be very stressful.", th: "ในขณะที่ชีวิตในเมืองน่าตื่นเต้น มันก็ทำให้เครียดได้เช่นกัน" },
            { en: "You can borrow my laptop, provided that you return it by tomorrow.", th: "ยืมแล็ปท็อปฉันไปได้ แต่ขอให้เอามาคืนภายในพรุ่งนี้นะ" },
            { en: "Provided that the weather is good, we'll go ahead with the plan.", th: "ถ้าอากาศดี เราก็จะดำเนินแผนต่อไป" },
            { en: "In spite of being tired, she finished all her work.", th: "ทั้งที่เหนื่อย เธอก็ทำงานทั้งหมดจนเสร็จ" },
            { en: "In spite of the rain, the outdoor event went really well.", th: "แม้จะมีฝน งานกลางแจ้งก็จัดได้ดีมาก" },
            { en: "As long as you try your best, that's enough.", th: "ตราบใดที่ทำเต็มที่แล้ว ก็เพียงพอแล้ว" },
            { en: "As long as I have my laptop, I can work from anywhere.", th: "ตราบใดที่ยังมีแล็ปท็อป ฉันทำงานจากที่ไหนก็ได้" },
            { en: "Due to heavy traffic, the meeting started late.", th: "เนื่องจากรถติดหนัก การประชุมเลยเริ่มช้า" },
            { en: "The project failed due to a lack of proper planning.", th: "โปรเจกต์ล้มเหลวเพราะขาดการวางแผนที่ดี" },
            { en: "I studied hard; as a result, I passed the exam.", th: "ฉันอ่านหนังสือหนัก ส่งผลให้สอบผ่าน" },
            { en: "In addition to studying, she also works part-time.", th: "นอกจากเรียนแล้ว เธอยังทำงานพาร์ทไทม์ด้วย" },
            { en: "I'll join you, as long as we don't stay too late.", th: "ฉันจะไปด้วย ขอแค่อย่าอยู่ดึกมากนะ" },
        ]
    },
];

window.ESB_Sessions.push({
    id: 'session-2-1',
    title: 'Session 2.1: Grammar Gaps',
    data: Part21Data,
    defaultOpen: false
});


