// ข้อมูลหมวดหมู่ของ Session 2
const Part2Data = [
    {
        id: 'A2', title: 'A. Past Experiences & Narratives', color: 'bg-indigo-50 border-indigo-200 text-indigo-900',
        sentences: [
            { en: "I went to the grocery store yesterday afternoon.", th: "ฉันไปร้านขายของชำเมื่อวานตอนบ่าย" },
            { en: "I went to a really interesting conference last month.", th: "ฉันไปงานประชุมที่น่าสนใจมากเมื่อเดือนที่แล้ว" },
            { en: "I went to high school in a different city.", th: "ฉันเรียนมัธยมปลายในเมืองอื่น" },
            { en: "I saw a strange man standing outside.", th: "ฉันเห็นผู้ชายแปลกๆ ยืนอยู่ข้างนอก" },
            { en: "I saw that movie a couple of years ago.", th: "ฉันดูหนังเรื่องนั้นเมื่อสองสามปีก่อน" },
            { en: "I visited my grandparents over the weekend.", th: "ฉันไปเยี่ยมปู่ย่าตายายช่วงสุดสัปดาห์" },
            { en: "I stayed at home and relaxed all day.", th: "ฉันอยู่บ้านและพักผ่อนทั้งวัน" },
            { en: "I finished my project just in time.", th: "ฉันทำโปรเจกต์เสร็จทันเวลาพอดี" },
            { en: "I started learning to play the guitar recently.", th: "ฉันเพิ่งเริ่มเรียนกีตาร์เมื่อไม่นานมานี้" },
            { en: "I bought a new laptop because my old one broke.", th: "ฉันซื้อแล็ปท็อปใหม่เพราะเครื่องเก่าพัง" },
            { en: "I didn't have time to eat breakfast this morning.", th: "ฉันไม่มีเวลากินมื้อเช้าเมื่อเช้านี้" },
            { en: "I didn't know you were coming today.", th: "ฉันไม่รู้ว่าวันนี้คุณจะมา" },
            { en: "I didn't realize it was so late.", th: "ฉันไม่ทันสังเกตว่ามันดึกขนาดนี้แล้ว" },
            { en: "I didn't expect to see you here.", th: "ฉันไม่คิดว่าจะเจอคุณที่นี่" },
            { en: "I didn't mean to hurt your feelings.", th: "ฉันไม่ได้ตั้งใจจะทำร้ายความรู้สึกคุณ" },
            { en: "I didn't get your message until later.", th: "ฉันเพิ่งได้รับข้อความของคุณทีหลัง" },
            { en: "I didn't sleep very well last night.", th: "เมื่อคืนฉันนอนไม่ค่อยหลับ" },
            { en: "I didn't go out because it was raining heavily.", th: "ฉันไม่ได้ออกไปข้างนอกเพราะฝนตกหนัก" },
            { en: "I didn't like the food at that restaurant.", th: "ฉันไม่ชอบอาหารที่ร้านนั้นเลย" },
            { en: "I didn't understand what he was saying.", th: "ฉันไม่เข้าใจว่าเขาพูดอะไร" },
            { en: "Did you have a good weekend?", th: "สุดสัปดาห์ที่ผ่านมาดีไหม?" },
            { en: "Did you manage to finish the report?", th: "คุณทำรายงานเสร็จทันไหม?" },
            { en: "Did you hear about the news?", th: "คุณได้ยินข่าวหรือยัง?" },
            { en: "Did you enjoy the party last night?", th: "ปาร์ตี้เมื่อคืนสนุกไหม?" },
            { en: "Did you find what you were looking for?", th: "คุณหาของที่ต้องการเจอหรือยัง?" },
            { en: "Did you get home safely?", th: "คุณกลับถึงบ้านปลอดภัยไหม?" },
            { en: "Did you see the email I sent you?", th: "คุณเห็นอีเมลที่ฉันส่งให้ไหม?" },
            { en: "Did you watch the game yesterday?", th: "เมื่อวานคุณดูการแข่งขันไหม?" },
            { en: "Where did you grow up?", th: "คุณโตที่ไหน?" },
            { en: "Where did you buy those shoes?", th: "คุณซื้อรองเท้าคู่นั้นที่ไหน?" },
            { en: "When did you arrive?", th: "คุณมาถึงเมื่อไหร่?" },
            { en: "When did you start working here?", th: "คุณเริ่มทำงานที่นี่เมื่อไหร่?" },
            { en: "Why did you leave so early?", th: "ทำไมคุณกลับเร็วจัง?" },
            { en: "Why did you choose this university?", th: "ทำไมคุณถึงเลือกมหาวิทยาลัยนี้?" },
            { en: "How did you fix the problem?", th: "คุณแก้ปัญหานั้นยังไง?" }
        ]
    },
    {
        id: 'B2', title: 'B. Continuous Actions in the Past', color: 'bg-orange-50 border-orange-200 text-orange-900',
        sentences: [
            { en: "I was working late last night.", th: "เมื่อคืนฉันทำงานดึก" },
            { en: "I was waiting for the bus when it started to rain.", th: "ฉันกำลังรอรถเมล์ตอนที่ฝนเริ่มตก" },
            { en: "I was thinking about you earlier.", th: "เมื่อกี้ฉันกำลังคิดถึงคุณอยู่" },
            { en: "I was wondering if you were free.", th: "ฉันกำลังสงสัยว่าคุณว่างไหม" },
            { en: "I was trying to call you, but the line was busy.", th: "ฉันพยายามโทรหาคุณ แต่สายไม่ว่าง" },
            { en: "I was watching TV when the power went out.", th: "ฉันกำลังดูทีวีตอนไฟดับ" },
            { en: "I was cooking dinner when the guests arrived.", th: "ฉันกำลังทำมื้อเย็นตอนที่แขกมาถึง" },
            { en: "I was cleaning my room all morning.", th: "ฉันทำความสะอาดห้องตลอดทั้งเช้า" },
            { en: "I was feeling a bit sick yesterday.", th: "เมื่อวานฉันรู้สึกป่วยนิดหน่อย" },
            { en: "I was driving to work when I saw the accident.", th: "ฉันกำลังขับรถไปทำงานตอนที่เห็นอุบัติเหตุ" },
            { en: "We were talking about our holiday plans.", th: "พวกเรากำลังคุยกันเรื่องแผนวันหยุด" },
            { en: "We were having lunch when you called.", th: "พวกเรากำลังกินมื้อเที่ยงตอนที่คุณโทรมา" },
            { en: "We were walking in the park.", th: "พวกเรากำลังเดินเล่นในสวน" },
            { en: "They were arguing about money.", th: "พวกเขากำลังทะเลาะกันเรื่องเงิน" },
            { en: "They were playing loud music all night.", th: "พวกเขาเปิดเพลงเสียงดังทั้งคืน" },
            { en: "What were you doing at 8 p.m.?", th: "ตอน 2 ทุ่มคุณกำลังทำอะไรอยู่?" },
            { en: "What were you talking about?", th: "คุณกำลังคุยเรื่องอะไรกัน?" },
            { en: "What were you thinking?", th: "คุณกำลังคิดอะไรอยู่?" },
            { en: "Where were you going when I saw you?", th: "ตอนที่ฉันเห็นคุณ คุณกำลังจะไปไหน?" },
            { en: "Who were you talking to on the phone?", th: "คุณกำลังคุยโทรศัพท์กับใคร?" }
        ]
    },
    {
        id: 'C2', title: 'C. Life Experiences (Present Perfect)', color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
        sentences: [
            { en: "I have finished my homework.", th: "ฉันทำการบ้านเสร็จแล้ว" },
            { en: "I have seen that movie three times.", th: "ฉันดูหนังเรื่องนั้นมา 3 รอบแล้ว" },
            { en: "I have been to Paris twice.", th: "ฉันเคยไปปารีสมา 2 ครั้ง" },
            { en: "I have lost my keys again.", th: "ฉันทำกุญแจหายอีกแล้ว" },
            { en: "I have forgotten his name.", th: "ฉันลืมชื่อเขาไปแล้ว" },
            { en: "I have read that book already.", th: "ฉันอ่านหนังสือนั้นแล้ว" },
            { en: "I have decided to quit my job.", th: "ฉันตัดสินใจลาออกจากงานแล้ว" },
            { en: "I have heard a lot about you.", th: "ฉันได้ยินเรื่องของคุณมาเยอะมาก" },
            { en: "I have known her for ten years.", th: "ฉันรู้จักเธอมา 10 ปีแล้ว" },
            { en: "I have lived here since 2015.", th: "ฉันอยู่ที่นี่มาตั้งแต่ปี 2015" },
            { en: "I’ve just arrived at the station.", th: "ฉันเพิ่งมาถึงสถานี" },
            { en: "I’ve just sent you the file.", th: "ฉันเพิ่งส่งไฟล์ให้คุณ" },
            { en: "I’ve just finished eating.", th: "ฉันเพิ่งกินข้าวเสร็จ" },
            { en: "I’ve just realized something important.", th: "ฉันเพิ่งนึกเรื่องสำคัญออก" },
            { en: "I’ve never eaten sushi before.", th: "ฉันไม่เคยทานซูชิมาก่อน" },
            { en: "I’ve never been to South America.", th: "ฉันไม่เคยไปอเมริกาใต้" },
            { en: "I’ve never met him in person.", th: "ฉันไม่เคยเจอเขาตัวเป็นๆ" },
            { en: "I’ve never tried skydiving.", th: "ฉันไม่เคยลองกระโดดร่ม" },
            { en: "I’ve never heard of that band.", th: "ฉันไม่เคยได้ยินชื่อวงนั้นมาก่อน" },
            { en: "I haven't seen you for ages.", th: "ไม่ได้เจอกันนานมากเลยนะ" },
            { en: "I haven't finished it yet.", th: "ฉันยังทำไม่เสร็จเลย" },
            { en: "I haven't decided where to go.", th: "ฉันยังไม่ได้ตัดสินใจว่าจะไปไหน" },
            { en: "I haven't received the package.", th: "ฉันยังไม่ได้รับพัสดุเลย" },
            { en: "I haven't had time to do it.", th: "ฉันยังไม่มีเวลาทำมันเลย" },
            { en: "Have you ever been to Thailand?", th: "คุณเคยไปประเทศไทยไหม?" },
            { en: "Have you ever tried Korean food?", th: "คุณเคยลองอาหารเกาหลีไหม?" },
            { en: "Have you ever lost your wallet?", th: "คุณเคยทำกระเป๋าตังค์หายไหม?" },
            { en: "Have you ever broken a bone?", th: "คุณเคยกระดูกหักไหม?" },
            { en: "Have you seen the new Spider-Man movie?", th: "คุณดูสไปเดอร์แมนภาคใหม่หรือยัง?" },
            { en: "Have you finished your work yet?", th: "คุณทำงานเสร็จหรือยัง?" },
            { en: "Have you found a new apartment yet?", th: "คุณหาอะพาร์ตเมนต์ใหม่ได้หรือยัง?" },
            { en: "Have you heard from him recently?", th: "ช่วงนี้ได้ข่าวจากเขาบ้างไหม?" },
            { en: "How long have you lived here?", th: "คุณอยู่ที่นี่มานานแค่ไหนแล้ว?" },
            { en: "How long have you worked for this company?", th: "คุณทำงานบริษัทนี้มานานเท่าไหร่แล้ว?" },
            { en: "How long have you been waiting?", th: "คุณรอมานานแค่ไหนแล้ว?" }
        ]
    },
    {
        id: 'D2', title: 'D. Past Habits & Changes (Used to)', color: 'bg-rose-50 border-rose-200 text-rose-900',
        sentences: [
            { en: "I used to smoke, but I quit last year.", th: "ฉันเคยสูบบุหรี่ แต่เลิกไปเมื่อปีที่แล้ว" },
            { en: "I used to live in a small village.", th: "ฉันเคยอยู่ในหมู่บ้านเล็กๆ" },
            { en: "I used to have long hair.", th: "ฉันเคยไว้ผมยาว" },
            { en: "I used to play football every weekend.", th: "ฉันเคยเตะบอลทุกสุดสัปดาห์" },
            { en: "I used to hate coffee, but now I love it.", th: "ฉันเคยเกลียดกาแฟ แต่ตอนนี้ชอบมาก" },
            { en: "I used to work in a restaurant.", th: "ฉันเคยทำงานร้านอาหาร" },
            { en: "I used to be very shy.", th: "ฉันเคยเป็นคนขี้อายมาก" },
            { en: "I used to go to the gym every day.", th: "ฉันเคยไปยิมทุกวัน" },
            { en: "I used to wake up early, but now I sleep in.", th: "ฉันเคยตื่นเช้า แต่เดี๋ยวนี้ตื่นสาย" },
            { en: "We used to be close friends.", th: "เราเคยเป็นเพื่อนสนิทกัน" },
            { en: "I didn't use to like vegetables.", th: "ฉันเคยไม่ชอบผัก" },
            { en: "I didn't use to exercise much.", th: "ฉันเคยไม่ค่อยออกกำลังกาย" },
            { en: "I didn't use to worry about money.", th: "ฉันไม่เคยต้องกังวลเรื่องเงิน (แต่ตอนนี้กังวล)" },
            { en: "Did you use to have a dog?", th: "คุณเคยเลี้ยงหมาไหม?" },
            { en: "Did you use to live near here?", th: "คุณเคยอยู่แถวนี้หรือเปล่า?" },
            { en: "Did you use to play video games?", th: "เมื่อก่อนคุณเล่นเกมไหม?" },
            { en: "Where did you use to go for holidays?", th: "เมื่อก่อนคุณชอบไปเที่ยวไหนช่วงวันหยุด?" },
            { en: "What did you use to do after school?", th: "เมื่อก่อนหลังเลิกเรียนคุณทำอะไร?" },
            { en: "It’s not like it used to be.", th: "มันไม่เหมือนเมื่อก่อนแล้ว" },
            { en: "I’m not as fit as I used to be.", th: "ฉันไม่ฟิตเหมือนเมื่อก่อนแล้ว" }
        ]
    },
    {
        id: 'E2', title: 'E. Future Plans & Intentions', color: 'bg-sky-50 border-sky-200 text-sky-900',
        sentences: [
            { en: "I’m going to buy a new car next month.", th: "ฉันกะว่าจะซื้อรถใหม่เดือนหน้า" },
            { en: "I’m going to visit my sister in London.", th: "ฉันจะไปเยี่ยมพี่สาวที่ลอนดอน" },
            { en: "I’m going to start a diet on Monday.", th: "ฉันจะเริ่มลดน้ำหนักวันจันทร์" },
            { en: "I’m going to look for a new job.", th: "ฉันจะหางานใหม่" },
            { en: "I’m going to take a few days off.", th: "ฉันจะลางานสักสองสามวัน" },
            { en: "I’m going to study harder this semester.", th: "เทอมนี้ฉันจะตั้งใจเรียนให้มากขึ้น" },
            { en: "I’m going to clean the house this weekend.", th: "ฉันจะทำความสะอาดบ้านสุดสัปดาห์นี้" },
            { en: "I’m going to ask for a promotion.", th: "ฉันจะขอเลื่อนตำแหน่ง" },
            { en: "It’s going to rain later.", th: "เดี๋ยวฝนน่าจะตก" },
            { en: "It’s going to be a long day.", th: "วันนี้คงเป็นวันที่ยาวนานแน่ๆ" },
            { en: "I’m meeting my boss tomorrow morning.", th: "พรุ่งนี้เช้าฉันมีนัดกับหัวหน้า" },
            { en: "I’m having dinner with Sarah tonight.", th: "คืนนี้ฉันนัดทานข้าวกับซาร่า" },
            { en: "I’m flying to New York next Friday.", th: "วันศุกร์หน้าฉันจะบินไปนิวยอร์ก" },
            { en: "I’m staying at a hotel downtown.", th: "ฉันพักที่โรงแรมในตัวเมือง" },
            { en: "I’m not doing anything special this weekend.", th: "สุดสัปดาห์นี้ฉันไม่ได้ทำอะไรพิเศษ" },
            { en: "We are getting married next summer.", th: "เราจะแต่งงานกันหน้าร้อนหน้า" },
            { en: "We are moving to a new house soon.", th: "เรากำลังจะย้ายบ้านเร็วๆ นี้" },
            { en: "They are coming to visit us.", th: "พวกเขากำลังจะมาเยี่ยมเรา" },
            { en: "What are you doing next week?", th: "อาทิตย์หน้าคุณจะทำอะไร?" },
            { en: "When are you leaving?", th: "คุณจะไปเมื่อไหร่?" }
        ]
    },
    {
        id: 'F2', title: 'F. Predictions & Promises (Will)', color: 'bg-yellow-50 border-yellow-200 text-yellow-900',
        sentences: [
            { en: "I’ll call you when I get home.", th: "ถึงบ้านแล้วเดี๋ยวฉันโทรหา" },
            { en: "I’ll text you the address.", th: "เดี๋ยวฉันส่งที่อยู่ไปให้" },
            { en: "I’ll help you with your homework.", th: "เดี๋ยวฉันช่วยทำการบ้าน" },
            { en: "I’ll pay for lunch today.", th: "มื้อเที่ยงวันนี้ฉันเลี้ยงเอง" },
            { en: "I’ll be back in five minutes.", th: "เดี๋ยวฉันกลับมาใน 5 นาที" },
            { en: "I’ll do my best.", th: "ฉันจะพยายามให้ดีที่สุด" },
            { en: "I won’t tell anyone your secret.", th: "ฉันจะไม่บอกความลับคุณกับใคร" },
            { en: "I won’t be late, I promise.", th: "ฉันสัญญาว่าจะไม่สาย" },
            { en: "I won’t forget to buy milk.", th: "ฉันจะไม่ลืมซื้อนม" },
            { en: "I won’t let you down.", th: "ฉันจะไม่ทำให้คุณผิดหวัง" },
            { en: "I think it will rain tomorrow.", th: "ฉันคิดว่าพรุ่งนี้ฝนน่าจะตก" },
            { en: "I think he will like the gift.", th: "ฉันว่าเขาน่าจะชอบของขวัญนะ" },
            { en: "I think we will win the game.", th: "ฉันว่าเราชนะเกมนี้แน่" },
            { en: "I don’t think it will be a problem.", th: "ฉันไม่คิดว่ามันจะเป็นปัญหานะ" },
            { en: "Maybe I’ll go to the cinema later.", th: "บางทีเดี๋ยวฉันอาจจะไปดูหนัง" },
            { en: "Maybe I’ll stay in tonight.", th: "คืนนี้ฉันอาจจะอยู่ห้องเฉยๆ" },
            { en: "Do you think it will work?", th: "คุณคิดว่ามันจะได้ผลไหม?" },
            { en: "Do you think she will say yes?", th: "คุณคิดว่าเธอจะตอบตกลงไหม?" },
            { en: "Where will you be in ten years?", th: "อีก 10 ปีคุณจะอยู่ที่ไหน?" },
            { en: "It will probably be expensive.", th: "มันน่าจะราคาแพงอยู่นะ" }
        ]
    },
    {
        id: 'G2', title: 'G. Conditions & Possibilities', color: 'bg-purple-50 border-purple-200 text-purple-900',
        sentences: [
            { en: "If I have time, I’ll help you.", th: "ถ้าฉันมีเวลา ฉันจะช่วยนะ" },
            { en: "If I see him, I’ll tell him you said hello.", th: "ถ้าเจอเขา ฉันจะบอกว่าคุณฝากทักทาย" },
            { en: "If it rains, we’ll stay inside.", th: "ถ้าฝนตก เราจะอยู่ข้างใน" },
            { en: "If I miss the bus, I’ll take a taxi.", th: "ถ้าตกรถเมล์ ฉันจะนั่งแท็กซี่ไป" },
            { en: "If you work hard, you’ll succeed.", th: "ถ้าคุณขยัน คุณจะประสบความสำเร็จ" },
            { en: "If you don’t hurry, you’ll be late.", th: "ถ้าไม่รีบ เดี๋ยวจะสายนะ" },
            { en: "If you don’t study, you won’t pass the exam.", th: "ถ้าไม่ดูหนังสือ คุณจะสอบไม่ผ่าน" },
            { en: "If the weather is nice, we’ll go to the beach.", th: "ถ้าอากาศดี เราจะไปชายหาดกัน" },
            { en: "If I get the job, I’ll be so happy.", th: "ถ้าได้งานนี้ ฉันจะดีใจมาก" },
            { en: "If I find your keys, I’ll let you know.", th: "ถ้าเจอกุญแจ เดี๋ยวฉันบอกนะ" },
            { en: "If you heat ice, it melts.", th: "ถ้านำน้ำแข็งไปให้ความร้อน มันจะละลาย" },
            { en: "If I drink coffee at night, I can’t sleep.", th: "ถ้าฉันดื่มกาแฟตอนกลางคืน ฉันจะนอนไม่หลับ" },
            { en: "If I am late, my boss gets angry.", th: "ถ้าฉันมาสาย เจ้านายจะโกรธ" },
            { en: "If you need anything, just call me.", th: "ถ้าต้องการอะไร โทรหาฉันได้เลย" },
            { en: "If you have any questions, please ask.", th: "ถ้ามีคำถาม ถามได้เลยครับ" },
            { en: "What will you do if it rains?", th: "ถ้าฝนตกคุณจะทำยังไง?" },
            { en: "What will you do if you lose your job?", th: "ถ้าตกงานคุณจะทำยังไง?" },
            { en: "Where will you go if the hotel is full?", th: "ถ้าโรงแรมเต็ม คุณจะไปที่ไหน?" },
            { en: "I’ll go to the party unless I’m too tired.", th: "ฉันจะไปงานปาร์ตี้ เว้นแต่ว่าฉันจะเหนื่อยเกินไป" },
            { en: "I won’t buy it unless it’s on sale.", th: "ฉันจะไม่ซื้อถ้มมันไม่ลดราคา" }
        ]
    },
    {
        id: 'H2', title: 'H. Reasons, Causes & Effects', color: 'bg-teal-50 border-teal-200 text-teal-900',
        sentences: [
            { en: "I stayed home because I was feeling sick.", th: "ฉันอยู่บ้านเพราะรู้สึกป่วย" },
            { en: "I like him because he is very funny.", th: "ฉันชอบเขาเพราะเขาตลกมาก" },
            { en: "I’m learning English because I want to travel.", th: "ฉันเรียนภาษาอังกฤษเพราะอยากไปเที่ยว" },
            { en: "I quit my job because the salary was low.", th: "ฉันลาออกเพราะเงินเดือนน้อย" },
            { en: "I was late because my alarm didn’t go off.", th: "ฉันมาสายเพราะนาฬิกาปลุกไม่ดัง" },
            { en: "Since it’s raining, let’s take a taxi.", th: "ไหนๆ ฝนก็ตกแล้ว นั่งแท็กซี่กันเถอะ" },
            { en: "Since you are here, can you help me?", th: "ไหนๆ คุณก็อยู่ที่นี่แล้ว ช่วยฉันหน่อยได้ไหม?" },
            { en: "As I was tired, I went to bed early.", th: "เนื่องจากฉันเหนื่อย ฉันเลยเข้านอนเร็ว" },
            { en: "The reason I’m calling is to apologize.", th: "เหตุผลที่ฉันโทรมาคือจะขอโทษ" },
            { en: "The main reason is that I don’t have time.", th: "เหตุผลหลักคือฉันไม่มีเวลา" },
            { en: "I was tired, so I went to bed.", th: "ฉันเหนื่อย ฉันก็เลยไปนอน" },
            { en: "It was raining, so we cancelled the picnic.", th: "ฝนตก เราก็เลยยกเลิกปิกนิก" },
            { en: "I didn’t study, so I failed the test.", th: "ฉันไม่ได้อ่านหนังสือ ก็เลยสอบตก" },
            { en: "The shop was closed, so I came back home.", th: "ร้านปิด ฉันก็เลยกลับบ้าน" },
            { en: "I want to be healthy, so I exercise daily.", th: "ฉันอยากสุขภาพดี ก็เลยออกกำลังกายทุกวัน" },
            { en: "I hate flying, that’s why I took the train.", th: "ฉันเกลียดการนั่งเครื่องบิน นั่นคือเหตุผลที่ฉันนั่งรถไฟ" },
            { en: "He lied to me, that’s why I’m angry.", th: "เขาโกหกฉัน นั่นคือเหตุผลที่ฉันโกรธ" },
            { en: "I need money, that’s why I’m working overtime.", th: "ฉันร้อนเงิน นั่นคือเหตุผลที่ฉันทำงานล่วงเวลา" },
            { en: "The traffic was bad; therefore, I was late.", th: "การจราจรแย่มาก ด้วยเหตุนี้ฉันจึงมาสาย" },
            { en: "He didn't answer; therefore, I left a message.", th: "เขาไม่รับสาย ฉันจึงฝากข้อความไว้" }
        ]
    },
    {
        id: 'I2', title: 'I. Contrasts & Concessions', color: 'bg-pink-50 border-pink-200 text-pink-900',
        sentences: [
            { en: "Although it was raining, we went out.", th: "ถึงแม้ฝนจะตก เราก็ออกไปข้างนอก" },
            { en: "Although he is old, he is very active.", th: "ถึงเขาจะแก่ แต่เขากระฉับกระเฉงมาก" },
            { en: "Although I studied hard, I failed.", th: "ถึงฉันจะเรียนหนัก แต่ก็สอบตก" },
            { en: "Even though I was tired, I kept working.", th: "ถึงแม้ฉันจะเหนื่อย แต่ฉันก็ทำต่อไป" },
            { en: "Even though it’s expensive, I want to buy it.", th: "ถึงมันจะแพง แต่ฉันก็อยากได้" },
            { en: "Even though I like her, I can’t live with her.", th: "ถึงฉันจะชอบเธอ แต่ฉันอยู่กับเธอไม่ได้" },
            { en: "I enjoyed the party, although I didn’t know anyone.", th: "ฉันสนุกกับงานปาร์ตี้ ถึงแม้จะไม่รู้จักใครเลย" },
            { en: "I bought the car, even though it was used.", th: "ฉันซื้อรถคันนั้น ถึงแม้มันจะเป็นรถมือสอง" },
            { en: "She is very nice, though she can be strict.", th: "เธอนิสัยดีนะ ถึงแม้จะเข้มงวดไปบ้าง" },
            { en: "It was a good movie, though it was a bit long.", th: "หนังดีนะ ถึงจะยาวไปหน่อย" },
            { en: "I wanted to go, but I was too busy.", th: "ฉันอยากไปนะ แต่ยุ่งมาก" },
            { en: "The food was good, but the service was slow.", th: "อาหารอร่อย แต่บริการช้า" },
            { en: "I like this phone; however, it is too big.", th: "ฉันชอบมือถือเครื่องนี้นะ แต่อย่างไรก็ตาม มันใหญ่ไป" },
            { en: "He is very smart; however, he is lazy.", th: "เขาฉลาดมาก แต่ติดที่ขี้เกียจ" },
            { en: "I love the city. On the other hand, it’s very noisy.", th: "ฉันรักในตัวเมืองนะ แต่อีกมุมหนึ่ง มันเสียงดังมาก" },
            { en: "Driving is fast. On the other hand, parking is difficult.", th: "ขับรถมันเร็ว แต่อีกมุมหนึ่งหาที่จอดยาก" },
            { en: "Living alone is free. On the other hand, it’s lonely.", th: "อยู่คนเดียวมันอิสระ แต่อีกมุมหนึ่งมันก็เหงา" },
            { en: "While I like coffee, I prefer tea in the morning.", th: "ในขณะที่ฉันชอบกาแฟ แต่ตอนเช้าฉันชอบชามากกว่า" },
            { en: "While London is exciting, it is also expensive.", th: "ในขณะที่ลอนดอนน่าตื่นตาตื่นใจ มันก็แพงด้วย" },
            { en: "Unlike my brother, I am very quiet.", th: "ต่างจากพี่ชายของฉัน ฉันเป็นคนเงียบๆ" }
        ]
    },
    {
        id: 'J2', title: 'J. Opinions, Agreements & Disagreements', color: 'bg-lime-50 border-lime-200 text-lime-900',
        sentences: [
            { en: "I think we should leave now.", th: "ฉันคิดว่าเราควรไปกันได้แล้ว" },
            { en: "I don't think that's a good idea.", th: "ฉันไม่คิดว่านั่นเป็นไอเดียที่ดีนะ" },
            { en: "I honestly think it’s the best option.", th: "ฉันคิดจริงๆ ว่านี่คือทางเลือกที่ดีที่สุด" },
            { en: "In my opinion, the movie was boring.", th: "ในความคิดฉันนะ หนังน่าเบื่อมาก" },
            { en: "In my opinion, technology is useful.", th: "ในความคิดฉัน เทคโนโลยีมีประโยชน์" },
            { en: "From my point of view, it’s not fair.", th: "ในมุมมองของฉัน มันไม่ยุติธรรม" },
            { en: "As far as I’m concerned, the matter is closed.", th: "สำหรับฉัน เรื่องนี้จบไปแล้ว" },
            { en: "If you ask me, it’s too expensive.", th: "ถ้าถามฉันนะ มันแพงไป" },
            { en: "I believe that we can do better.", th: "ฉันเชื่อว่าเราทำได้ดีกว่านี้" },
            { en: "I strongly believe that education is important.", th: "ฉันเชื่ออย่างยิ่งว่าการศึกษาเป็นสิ่งสำคัญ" },
            { en: "I agree with you up to a point.", th: "ฉันเห็นด้วยกับคุณในระดับหนึ่ง" },
            { en: "I completely agree with you.", th: "ฉันเห็นด้วยกับคุณแบบสุดๆ" },
            { en: "I see what you mean, but I disagree.", th: "ฉันเข้าใจที่คุณพูดนะ แต่ฉันไม่เห็นด้วย" },
            { en: "That’s a good point, but it’s risky.", th: "เป็นประเด็นที่ดี แต่มันเสี่ยง" },
            { en: "You’re right about that.", th: "เรื่องนั้นคุณพูดถูก" },
            { en: "That’s exactly what I think.", th: "นั่นคือสิ่งที่ฉันคิดเป๊ะเลย" },
            { en: "I’m afraid I have to disagree.", th: "เกรงว่าฉันต้องขอค้านนะ" },
            { en: "I’m not sure about that.", th: "ฉันไม่แน่ใจเรื่องนั้นเท่าไหร่" },
            { en: "It depends on the situation.", th: "มันก็ขึ้นอยู่กับสถานการณ์" },
            { en: "It depends on how much it costs.", th: "มันขึ้นอยู่กับว่าราคาเท่าไหร่" }
        ]
    },
    {
        id: 'K2', title: 'K. Time Relationships', color: 'bg-cyan-50 border-cyan-200 text-cyan-900',
        sentences: [
            { en: "When I get home, I will call you.", th: "เมื่อฉันถึงบ้าน ฉันจะโทรหานะ" },
            { en: "When I was a child, I lived in Tokyo.", th: "ตอนฉันเป็นเด็ก ฉันอาศัยในโตเกียว" },
            { en: "When you arrive, please wait in the lobby.", th: "เมื่อคุณมาถึง รอที่ล็อบบี้นะ" },
            { en: "While I was cooking, the phone rang.", th: "ตอนฉันกำลังทำกับข้าว โทรศัพท์ก็ดัง" },
            { en: "While you are out, can you buy some milk?", th: "ตอนคุณออกไปข้างนอก ฝากซื้อนมหน่อยได้ไหม?" },
            { en: "Please be quiet while I am on the phone.", th: "ช่วยเงียบหน่อยตอนฉันคุยโทรศัพท์" },
            { en: "Don't use your phone while you are driving.", th: "อย่าเล่นมือถือตอนขับรถ" },
            { en: "I fell asleep while I was reading.", th: "ฉันเผลอหลับตอนกำลังอ่านหนังสือ" },
            { en: "As soon as I finish, I will let you know.", th: "ทันทีที่ฉันทำเสร็จ ฉันจะบอกนะ" },
            { en: "As soon as you see him, tell me.", th: "ทันทีที่เจอเขา บอกฉันด้วย" },
            { en: "Before I go to bed, I always brush my teeth.", th: "ก่อนเข้านอน ฉันแปรงฟันเสมอ" },
            { en: "Before you leave, please turn off the lights.", th: "ก่อนคุณไป ช่วยปิดไฟด้วย" },
            { en: "After I finished work, I went to the gym.", th: "หลังจากทำงานเสร็จ ฉันไปยิม" },
            { en: "After we eat, let’s go for a walk.", th: "หลังจากกินเสร็จ ไปเดินเล่นกันเถอะ" },
            { en: "I can’t go out until I finish this.", th: "ฉันออกไปไม่ได้จนกว่าจะทำนี่เสร็จ" },
            { en: "I will wait here until you come back.", th: "ฉันจะรอตรงนี้จนกว่าคุณจะกลับมา" },
            { en: "We stayed at the party until midnight.", th: "เราอยู่ที่ปาร์ตี้จนถึงเที่ยงคืน" },
            { en: "By the time I arrived, they had left.", th: "กว่าฉันจะไปถึง พวกเขาก็กลับไปแล้ว" },
            { en: "During the meeting, I took notes.", th: "ระหว่างประชุม ฉันจดบันทึกไปด้วย" },
            { en: "During the flight, I watched two movies.", th: "ระหว่างบิน ฉันดูหนังไป 2 เรื่อง" }
        ]
    },
    {
        id: 'L2', title: 'L. Problems & Suggestions', color: 'bg-red-50 border-red-200 text-red-900',
        sentences: [
            { en: "I have a problem with my internet connection.", th: "ฉันมีปัญหากับสัญญาณอินเทอร์เน็ต" },
            { en: "There is something wrong with the air conditioner.", th: "แอร์มีปัญหาบางอย่าง" },
            { en: "I’m having trouble finding the location.", th: "ฉันกำลังหาตำแหน่งไม่เจอ" },
            { en: "I’m having trouble understanding this grammar.", th: "ฉันงงกับไวยากรณ์เรื่องนี้มาก" },
            { en: "It seems like the server is down.", th: "ดูเหมือนว่าเซิร์ฟเวอร์จะล่ม" },
            { en: "The battery keeps dying.", th: "แบตเตอรี่หมดเร็วมาก/ดับตลอด" },
            { en: "The car broke down on the highway.", th: "รถเสียบนทางด่วน" },
            { en: "I ran out of gas.", th: "น้ำมันรถหมด" },
            { en: "I ran out of money.", th: "เงินฉันหมดแล้ว" },
            { en: "I ran out of patience.", th: "ฉันหมดความอดทนแล้ว" },
            { en: "You should see a doctor.", th: "คุณควรไปหาหมอนะ" },
            { en: "You shouldn't smoke so much.", th: "คุณไม่ควรสูบบุหรี่เยอะขนาดนั้น" },
            { en: "You should probably call him back.", th: "คุณน่าจะโทรกลับหาเขานะ" },
            { en: "Why don't you try restarting the computer?", th: "ทำไมไม่ลองรีสตาร์ทคอมดูล่ะ?" },
            { en: "Why don't we take a break?", th: "ทำไมเราไม่พักกันหน่อยล่ะ?" },
            { en: "How about going to the cinema?", th: "ไปดูหนังกันไหม?" },
            { en: "How about asking for help?", th: "ลองขอความช่วยเหลือดูไหม?" },
            { en: "If I were you, I would apologize.", th: "ถ้าฉันเป็นคุณ ฉันจะขอโทษ" },
            { en: "If I were you, I wouldn't do that.", th: "ถ้าฉันเป็นคุณ ฉันจะไม่ทำแบบนั้น" },
            { en: "I suggest that we wait a bit longer.", th: "ฉันแนะนำว่าเรารออีกหน่อยดีกว่า" }
        ]
    },
    {
        id: 'M2', title: 'M. Work, Study & Formal Communication', color: 'bg-slate-100 border-slate-300 text-slate-800',
        sentences: [
            { en: "I would like to make an appointment.", th: "ฉันต้องการขอนัดหมาย" },
            { en: "I would like to ask about the job opening.", th: "ฉันอยากสอบถามเรื่องตำแหน่งงานว่าง" },
            { en: "I would like to complain about the service.", th: "ฉันต้องการร้องเรียนเรื่องการบริการ" },
            { en: "Could you please send me the details?", th: "รบกวนส่งรายละเอียดให้ฉันหน่อยได้ไหม?" },
            { en: "Could you please confirm the meeting time?", th: "รบกวนช่วยยืนยันเวลานัดหมายได้ไหม?" },
            { en: "Could you let me know if you are available?", th: "ช่วยแจ้งให้ทราบหน่อยได้ไหมถ้าคุณว่าง?" },
            { en: "I am writing to inform you that I will be away.", th: "ฉันเขียนมาเพื่อแจ้งว่าฉันจะไม่อยู่" },
            { en: "I am interested in applying for this position.", th: "ฉันสนใจสมัครงานตำแหน่งนี้" },
            { en: "I look forward to hearing from you.", th: "ฉันหวังว่าจะได้รับการติดต่อกลับจากคุณ" },
            { en: "I look forward to meeting you.", th: "ฉันตั้งตารอที่จะได้พบคุณ" },
            { en: "Thank you for your patience.", th: "ขอบคุณที่อดทนรอ" },
            { en: "Thank you for your cooperation.", th: "ขอบคุณสำหรับความร่วมมือ" },
            { en: "Please find the attached file.", th: "โปรดดูไฟล์ที่แนบมา" },
            { en: "Please do not hesitate to contact me.", th: "อย่าลังเลที่จะติดต่อฉัน" },
            { en: "According to the report, sales are up.", th: "อ้างอิงจากรายงาน ยอดขายเพิ่มขึ้น" }
        ]
    },
    {
        id: 'N2', title: 'N. Feelings & Personal Growth', color: 'bg-fuchsia-50 border-fuchsia-200 text-fuchsia-900',
        sentences: [
            { en: "I realized that I made a mistake.", th: "ฉันรู้ตัวว่าทำพลาดไปแล้ว" },
            { en: "I realized that I left my phone at home.", th: "ฉันเพิ่งนึกได้ว่าลืมมือถือไว้ที่บ้าน" },
            { en: "I found out that he was lying.", th: "ฉันมารู้ทีหลังว่าเขาโกหก" },
            { en: "I found out that the event was cancelled.", th: "ฉันมารู้ว่างานถูกยกเลิก" },
            { en: "I was surprised to see her there.", th: "ฉันแปลกใจที่เห็นเธอที่นั่น" },
            { en: "I was disappointed with the result.", th: "ฉันผิดหวังกับผลลัพธ์" },
            { en: "I was excited about the trip.", th: "ฉันตื่นเต้นกับทริปนี้มาก" },
            { en: "I felt embarrassed when I fell down.", th: "ฉันรู้สึกอายตอนที่หกล้ม" },
            { en: "I felt relieved when I passed the test.", th: "ฉันรู้สึกโล่งอกตอนสอบผ่าน" },
            { en: "I’m worried about the future.", th: "ฉันกังวลเรื่องอนาคต" },
            { en: "I’m proud of my achievements.", th: "ฉันภูมิใจในความสำเร็จของตัวเอง" },
            { en: "It makes me feel happy.", th: "มันทำให้ฉันมีความสุข" },
            { en: "It makes me feel uncomfortable.", th: "มันทำให้ฉันรู้สึกอึดอัด" },
            { en: "It drives me crazy.", th: "มันทำให้ฉันจะบ้าตาย" },
            { en: "It gets on my nerves.", th: "มันกวนประสาทฉันมาก" }
        ]
    },
    {
        id: 'O2', title: 'O. Technology & Online Life', color: 'bg-blue-50 border-blue-200 text-blue-900',
        sentences: [
            { en: "My computer crashed while I was saving the file.", th: "คอมฉันค้างตอนกำลังเซฟไฟล์" },
            { en: "I accidentally deleted the photos.", th: "ฉันเผลอลบรูปไปโดยไม่ได้ตั้งใจ" },
            { en: "I can’t log in because I forgot my password.", th: "ฉันเข้าสู่ระบบไม่ได้เพราะลืมรหัส" },
            { en: "You need to update the software to fix the bug.", th: "คุณต้องอัปเดตซอฟต์แวร์เพื่อแก้บั๊ก" },
            { en: "Have you backed up your data?", th: "คุณสำรองข้อมูลหรือยัง?" },
            { en: "The Wi-Fi signal is very weak in this room.", th: "สัญญาณไวไฟในห้องนี้อ่อนมาก" },
            { en: "I spend too much time scrolling through social media.", th: "ฉันใช้เวลาไถโซเชียลมากเกินไป" },
            { en: "I saw your post on Facebook yesterday.", th: "ฉันเห็นโพสต์เฟซบุ๊กคุณเมื่อวาน" },
            { en: "Did you see the video that went viral?", th: "คุณเห็นวิดีโอที่เป็นไวรัลไหม?" },
            { en: "I usually shop online because it’s convenient.", th: "ปกติฉันช้อปออนไลน์เพราะมันสะดวก" },
            { en: "I downloaded the app, but it doesn't work.", th: "ฉันโหลดแอปมาแล้ว แต่มันใช้ไม่ได้" },
            { en: "I unsubscribed from the newsletter.", th: "ฉันกดยกเลิกรับข่าวสารทางอีเมลแล้ว" },
            { en: "Please mute your microphone during the call.", th: "ช่วยปิดไมค์ระหว่างโทรด้วยครับ" },
            { en: "Can you share your screen with us?", th: "ช่วยแชร์หน้าจอให้ดูหน่อยได้ไหม?" },
            { en: "The video is buffering.", th: "วิดีโอมันกำลังหมุนติ้วๆ (โหลดไม่ทัน)" }
        ]
    },
    {
        id: 'P2', title: 'P. Polite Requests (Mind/Wonder)', color: 'bg-indigo-50 border-indigo-200 text-indigo-900',
        sentences: [
            { en: "Do you mind if I sit here?", th: "จะว่าอะไรไหมถ้าฉันนั่งตรงนี้?" },
            { en: "Do you mind if I open the window?", th: "จะว่าอะไรไหมถ้าฉันเปิดหน้าต่าง?" },
            { en: "Do you mind helping me with this?", th: "รบกวนช่วยฉันเรื่องนี้หน่อยได้ไหม?" },
            { en: "Would you mind waiting a moment?", th: "รบกวนรอสักครู่ได้ไหมครับ?" },
            { en: "Would you mind keeping the noise down?", th: "รบกวนช่วยเบาเสียงหน่อยได้ไหม?" },
            { en: "I don't mind waiting.", th: "ฉันรอได้ ไม่เป็นไร" },
            { en: "I don't mind walking.", th: "ฉันเดินได้ ไม่ติดขัดอะไร" },
            { en: "I was wondering if you could help me.", th: "พอดีฉันอยากรู้ว่าคุณพอจะช่วยฉันได้ไหม" },
            { en: "I was wondering if you are free tonight.", th: "ฉันอยากรู้ว่าคืนนี้คุณว่างไหม" },
            { en: "I was wondering where the bathroom is.", th: "พอดีฉันอยากทราบว่าห้องน้ำไปทางไหน" }
        ]
    },
    {
        id: 'Q2', title: 'Q. Uncertainty & Speculation', color: 'bg-violet-50 border-violet-200 text-violet-900',
        sentences: [
            { en: "It might rain later, so take an umbrella.", th: "ฝนอาจจะตก พกร่มไปด้วยนะ" },
            { en: "He might be late.", th: "เขาอาจจะมาสาย" },
            { en: "She might not come today.", th: "วันนี้เธออาจจะไม่มา" },
            { en: "It could be true.", th: "มันอาจจะเป็นเรื่องจริงก็ได้" },
            { en: "It could be a misunderstanding.", th: "มันอาจจะเป็นความเข้าใจผิด" },
            { en: "I’m not sure what to do.", th: "ฉันไม่แน่ใจว่าจะทำยังไงดี" },
            { en: "I have no idea where he is.", th: "ฉันไม่รู้เลยว่าเขาอยู่ที่ไหน" },
            { en: "I doubt that it will happen.", th: "ฉันสงสัยว่ามันจะเกิดขึ้นจริงเหรอ (ไม่น่าเกิด)" },
            { en: "It looks like it’s going to snow.", th: "ดูเหมือนหิมะกำลังจะตก" },
            { en: "It sounds like a great idea.", th: "ฟังดูเป็นไอเดียที่เข้าท่ามาก" },
            { en: "It smells like something is burning.", th: "มีกลิ่นเหมือนอะไรไหม้" },
            { en: "It tastes a bit strange.", th: "รสชาติมันแปลกๆ นิดหน่อย" },
            { en: "It seems impossible.", th: "ดูเหมือนจะเป็นไปไม่ได้เลย" }
        ]
    },
    {
        id: 'R2', title: 'R. Common "Get" Phrases', color: 'bg-orange-50 border-orange-200 text-orange-900',
        sentences: [
            { en: "I need to get ready for work.", th: "ฉันต้องเตรียมตัวไปทำงาน" },
            { en: "I get along well with my colleagues.", th: "ฉันเข้ากับเพื่อนร่วมงานได้ดี" },
            { en: "I need to get rid of these old clothes.", th: "ฉันต้องกำจัดเสื้อผ้าเก่าพวกนี้" },
            { en: "I hope you get better soon.", th: "ขอให้หายไวๆ นะ" },
            { en: "It’s getting dark.", th: "เริ่มมืดแล้ว" },
            { en: "It’s getting late.", th: "เริ่มดึกแล้ว" },
            { en: "I’m getting used to the weather here.", th: "ฉันเริ่มชินกับอากาศที่นี่แล้ว" },
            { en: "I’m getting tired of this situation.", th: "ฉันเริ่มเบื่อกับสถานการณ์นี้แล้ว" },
            { en: "Did you get my message?", th: "ได้รับข้อความฉันไหม?" },
            { en: "How do I get to the airport?", th: "ฉันจะไปสนามบินได้ยังไง?" },
            { en: "I don’t get it.", th: "ฉันไม่เข้าใจ" },
            { en: "Let’s get started.", th: "มาเริ่มกันเถอะ" }
        ]
    },
    {
        id: 'S2', title: 'S. Quantity & Degree', color: 'bg-green-50 border-green-200 text-green-900',
        sentences: [
            { en: "It’s too hot to go outside.", th: "มันร้อนเกินกว่าจะออกไปข้างนอก" },
            { en: "It’s too expensive for me.", th: "มันแพงเกินไปสำหรับฉัน" },
            { en: "The music is too loud.", th: "เพลงเสียงดังเกินไป" },
            { en: "I’m too tired to cook.", th: "ฉันเหนื่อยเกินกว่าจะทำอาหาร" },
            { en: "He is too young to drive.", th: "เขาเด็กเกินกว่าจะขับรถ" },
            { en: "I don’t have enough money.", th: "ฉันมีเงินไม่พอ" },
            { en: "I don’t have enough time.", th: "ฉันมีเวลาไม่พอ" },
            { en: "This room isn’t big enough.", th: "ห้องนี้ใหญ่ไม่พอ" },
            { en: "It’s not warm enough to swim.", th: "อากาศไม่ร้อนพอที่จะว่ายน้ำ" },
            { en: "Did you buy enough food?", th: "ซื้ออาหารมาพอไหม?" }
        ]
    },
    {
        id: 'T2', title: 'T. Tag Questions', color: 'bg-pink-50 border-pink-200 text-pink-900',
        sentences: [
            { en: "You are coming, aren't you?", th: "คุณจะมา ใช่ไหม?" },
            { en: "You like coffee, don't you?", th: "คุณชอบกาแฟ ใช่ไหม?" },
            { en: "You didn't see him, did you?", th: "คุณไม่เห็นเขา ใช่ไหม?" },
            { en: "It’s a nice day, isn't it?", th: "อากาศดีเนอะ ว่าไหม?" },
            { en: "She is a doctor, isn't she?", th: "เธอเป็นหมอ ใช่ไหม?" },
            { en: "He can swim, can't he?", th: "เขาว่ายน้ำเป็น ใช่ไหม?" },
            { en: "We are late, aren't we?", th: "เราสายแล้ว ใช่ไหม?" },
            { en: "You have been there, haven't you?", th: "คุณเคยไปที่นั่น ใช่ไหม?" },
            { en: "They live in London, don't they?", th: "พวกเขาอยู่ที่ลอนดอน ใช่ไหม?" },
            { en: "You won't tell anyone, will you?", th: "คุณจะไม่บอกใคร ใช่ไหม?" }
        ]
    },
    {
        id: 'U2', title: 'U. Indirect Questions', color: 'bg-amber-50 border-amber-200 text-amber-900',
        sentences: [
            { en: "Can you tell me where the station is?", th: "ช่วยบอกหน่อยได้ไหมว่าสถานีอยู่ที่ไหน?" },
            { en: "Can you tell me what time it is?", th: "ช่วยบอกเวลาน่อยได้ไหม?" },
            { en: "Do you know who that man is?", th: "คุณรู้ไหมว่าผู้ชายคนนั้นเป็นใคร?" },
            { en: "Do you know when the bus leaves?", th: "คุณรู้ไหมว่ารถออกกี่โมง?" },
            { en: "Do you know if she is coming?", th: "คุณรู้ไหมว่าเธอจะมาหรือเปล่า?" },
            { en: "I’d like to know how much it costs.", th: "ฉันอยากทราบว่าราคาเท่าไหร่" },
            { en: "I’d like to know why you are late.", th: "ฉันอยากรู้ว่าทำไมคุณมาสาย" },
            { en: "Could you tell me where I can park?", th: "ช่วยบอกหน่อยได้ไหมว่าจอดรถตรงไหนได้บ้าง?" },
            { en: "Do you remember where we parked?", th: "จำได้ไหมว่าเราจอดรถไว้ไหน?" },
            { en: "Do you have any idea how to fix this?", th: "พอจะรู้วิธีซ่อมมันไหม?" }
        ]
    },
    {
        id: 'V2', title: 'V. Giving Advice & Warnings', color: 'bg-red-50 border-red-200 text-red-900',
        sentences: [
            { en: "Make sure you lock the door.", th: "อย่าลืมล็อคประตูนะ" },
            { en: "Make sure you don't forget your passport.", th: "อย่าลืมพาสปอร์ตเชียวนะ" },
            { en: "Watch out for the cars.", th: "ระวังรถด้วย" },
            { en: "Be careful with that knife.", th: "ระวังมีดเล่มนั้นด้วย" },
            { en: "You’d better hurry up.", th: "คุณรีบหน่อยดีกว่านะ" },
            { en: "You’d better not go there.", th: "คุณอย่าไปที่นั่นเลยจะดีกว่า" },
            { en: "Whatever you do, don't press that button.", th: "ไม่ว่าจะทำอะไร ห้ามกดปุ่มนั้นนะ" },
            { en: "Don't forget to call your mom.", th: "อย่าลืมโทรหาแม่นะ" },
            { en: "Remember to turn off the oven.", th: "อย่าลืมปิดเตาอบนะ" },
            { en: "Take care of yourself.", th: "ดูแลตัวเองด้วย" }
        ]
    },
    {
        id: 'W2', title: 'W. Regrets (Simple Wish)', color: 'bg-purple-50 border-purple-200 text-purple-900',
        sentences: [
            { en: "I wish I had more money.", th: "ฉันอยากมีเงินเยอะกว่านี้จัง (แต่ไม่มี)" },
            { en: "I wish I could fly.", th: "ฉันอยากบินได้" },
            { en: "I wish I didn't have to work today.", th: "ฉันอยากให้วันนี้ไม่ต้องทำงานจัง" },
            { en: "I wish I knew the answer.", th: "ฉันอยากรู้คำตอบจัง" },
            { en: "I wish I were taller.", th: "ฉันอยากสูงกว่านี้" },
            { en: "I wish it would stop raining.", th: "ฉันอยากให้ฝนหยุดตกสักที" },
            { en: "I wish you were here.", th: "ฉันอยากให้คุณอยู่ที่นี่จัง" },
            { en: "I should have studied harder.", th: "รู้งี้ฉันน่าจะตั้งใจเรียนให้มากกว่านี้" },
            { en: "I should have gone to bed earlier.", th: "รู้งี้ฉันน่าจะเข้านอนให้เร็วกว่านี้" },
            { en: "I shouldn't have said that.", th: "ฉันไม่น่าพูดแบบนั้นออกไปเลย" }
        ]
    },
    {
        id: 'X2', title: 'X. Relative Clauses', color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
        sentences: [
            { en: "That’s the man who helped me.", th: "นั่นคือคนที่ช่วยฉัน" },
            { en: "That’s the woman who lives next door.", th: "นั่นคือผู้หญิงที่อยู่ข้างบ้าน" },
            { en: "This is the book that I bought yesterday.", th: "นี่คือหนังสือที่ฉันซื้อเมื่อวาน" },
            { en: "This is the phone that I want.", th: "นี่คือมือถือที่ฉันอยากได้" },
            { en: "Do you know the girl who is singing?", th: "คุณรู้จักผู้หญิงคนที่กำลังร้องเพลงไหม?" },
            { en: "Where is the file that I sent you?", th: "ไฟล์ที่ฉันส่งให้คุณอยู่ที่ไหน?" },
            { en: "Is this the hotel where we are staying?", th: "นี่ใช่โรงแรมที่เราจะพักไหม?" },
            { en: "That’s the reason why I’m late.", th: "นั่นคือสาเหตุที่ฉันมาสาย" },
            { en: "He is someone who I can trust.", th: "เขาคือคนที่ฉันไว้ใจได้" },
            { en: "This is the best pizza that I’ve ever had.", th: "นี่คือพิซซ่าที่อร่อยที่สุดที่ฉันเคยกิน" }
        ]
    },
    {
        id: 'Y2', title: 'Y. Expressing Purpose', color: 'bg-cyan-50 border-cyan-200 text-cyan-900',
        sentences: [
            { en: "I went to the shop to buy milk.", th: "ฉันไปร้านค้าเพื่อซื้อนม" },
            { en: "I’m studying English to get a better job.", th: "ฉันเรียนภาษาอังกฤษเพื่อหางานที่ดีขึ้น" },
            { en: "I called him to apologize.", th: "ฉันโทรหาเขาเพื่อขอโทษ" },
            { en: "I went there to see my friends.", th: "ฉันไปที่นั่นเพื่อเจอเพื่อน" },
            { en: "This button is for turning on the machine.", th: "ปุ่มนี้มีไว้สำหรับเปิดเครื่อง" },
            { en: "This tool is for cutting wood.", th: "เครื่องมือนี้มีไว้ตัดไม้" },
            { en: "Is this seat for me?", th: "ที่นั่งนี้สำหรับฉันหรือเปล่า?" },
            { en: "Thank you for helping me.", th: "ขอบคุณที่ช่วยฉันนะ" },
            { en: "Thank you for inviting me.", th: "ขอบคุณที่เชิญฉันนะ" },
            { en: "I’m sorry for being late.", th: "ขอโทษที่มาสาย" }
        ]
    },
    {
        id: 'Z2', title: 'Z. Mixed Daily Situations', color: 'bg-slate-50 border-slate-200 text-slate-800',
        sentences: [
            { en: "To be honest, I don't really know.", th: "เอาตรงๆ นะ ฉันไม่รู้จริงๆ" },
            { en: "Actually, I have a different opinion.", th: "จริงๆ แล้วฉันมีความเห็นที่ต่างออกไป" },
            { en: "Basically, it’s a simple process.", th: "โดยพื้นฐานแล้ว มันเป็นขั้นตอนที่ง่ายๆ" },
            { en: "Suddenly, the lights went out.", th: "จู่ๆ ไฟก็ดับ" },
            { en: "Fortunately, no one was hurt.", th: "โชคดีที่ไม่มีใครบาดเจ็บ" },
            { en: "Unfortunately, I can’t make it.", th: "โชคร้ายที่ฉันไปไม่ได้" },
            { en: "Eventually, we found the right way.", th: "ในที่สุดเราก็หาทางที่ถูกเจอ" },
            { en: "Recently, I’ve been very busy.", th: "ช่วงนี้ฉันยุ่งมาก" },
            { en: "Currently, I am working on a new project.", th: "ปัจจุบันฉันกำลังทำโปรเจกต์ใหม่" },
            { en: "Generally, I wake up early.", th: "โดยทั่วไปฉันตื่นเช้า" },
            { en: "I managed to fix the car by myself.", th: "ฉันซ่อมรถด้วยตัวเองสำเร็จ" },
            { en: "I prefer cooking to washing dishes.", th: "ฉันชอบทำอาหารมากกว่าล้างจาน" },
            { en: "It takes about 20 minutes to get there.", th: "ใช้เวลาประมาณ 20 นาทีในการไปที่นั่น" },
            { en: "It took me two hours to finish the report.", th: "ฉันใช้เวลา 2 ชั่วโมงในการทำรายงานเสร็จ" },
            { en: "It’s worth trying.", th: "มันคุ้มค่าที่จะลองนะ" },
            { en: "It’s not worth the money.", th: "มันไม่คุ้มเงินเลย" },
            { en: "It’s no use worrying about it.", th: "กังวลไปก็เปล่าประโยชน์" },
            { en: "I’m looking forward to the weekend.", th: "ฉันตั้งตารอวันหยุดสุดสัปดาห์" },
            { en: "I’m interested in learning photography.", th: "ฉันสนใจเรียนถ่ายภาพ" },
            { en: "I’m good at solving problems.", th: "ฉันถนัดแก้ปัญหา" },
            { en: "I’m bad at remembering names.", th: "ฉันจำชื่อคนไม่เก่งเลย" },
            { en: "I’m afraid of heights.", th: "ฉันกลัวความสูง" },
            { en: "I’m tired of waiting.", th: "ฉันเบื่อที่จะรอแล้ว" },
            { en: "Are you familiar with this software?", th: "คุณคุ้นเคยกับซอฟต์แวร์นี้ไหม?" },
            { en: "Are you responsible for this project?", th: "คุณรับผิดชอบโปรเจกต์นี้ใช่ไหม?" },
            { en: "Is it possible to change the date?", th: "เป็นไปได้ไหมที่จะเปลี่ยนวัน?" },
            { en: "Is it necessary to print this?", th: "จำเป็นต้องปรินต์ไหม?" },
            { en: "Would you rather stay home or go out?", th: "คุณอยากอยู่บ้านหรือออกไปข้างนอกมากกว่ากัน?" },
            { en: "I’d rather go to the beach.", th: "ฉันอยากไปทะเลมากกว่า" },
            { en: "Let's keep in touch.", th: "แล้วติดต่อกันนะ" }
        ]
    }
];

// ดันข้อมูลลงในตัวแปรหลัก
window.ESB_Sessions.push({
    id: 'session-2',
    title: 'Session 2: Grammar & Patterns',
    data: Part2Data,
    defaultOpen: false
});