// ข้อมูลหมวดหมู่ของ Session 2.3 — Thai Context & Personal Scenarios
const Part23Data = [
    {
        id: 'A23', title: 'A. AI & Data Science — อธิบายงานให้คนอื่นฟัง', color: 'bg-violet-50 border-violet-200 text-violet-900',
        sentences: [
            { en: "I'm studying AI engineering and data science at university.", th: "ฉันเรียนวิศวกรรม AI กับดาต้าซายน์อยู่ที่มหาวิทยาลัย" },
            { en: "Basically, machine learning is teaching computers to learn from data.", th: "โดยพื้นฐานแล้ว machine learning ก็คือการสอนคอมพิวเตอร์ให้เรียนรู้จากข้อมูล" },
            { en: "The model I built can predict outcomes based on historical data.", th: "โมเดลที่ฉันสร้างสามารถพยากรณ์ผลลัพธ์จากข้อมูลในอดีตได้" },
            { en: "I'm currently working on a project that uses deep learning for image classification.", th: "ตอนนี้ฉันทำโปรเจกต์ที่ใช้ deep learning สำหรับแยกประเภทรูปภาพอยู่" },
            { en: "To put it simply, overfitting means the model memorized the training data too well.", th: "พูดง่ายๆ ก็คือ overfitting หมายความว่าโมเดลจำข้อมูลเทรนได้ดีเกินไป" },
            { en: "I used Python and scikit-learn to build the classification model.", th: "ฉันใช้ Python กับ scikit-learn ในการสร้างโมเดลจำแนกประเภท" },
            { en: "The accuracy of the model is around 92 percent on the test set.", th: "ความแม่นยำของโมเดลอยู่ที่ประมาณ 92 เปอร์เซ็นต์บน test set" },
            { en: "I'm still learning, but I find this field really fascinating.", th: "ฉันยังคงเรียนรู้อยู่ แต่รู้สึกว่าสาขานี้น่าสนใจมากจริงๆ" },
            { en: "Could you explain what you mean by neural network?", th: "ช่วยอธิบายหน่อยได้ไหมว่า neural network หมายความว่าอะไร?" },
            { en: "I'm preparing a presentation on the applications of NLP in healthcare.", th: "ฉันกำลังเตรียม presentation เรื่องการประยุกต์ใช้ NLP ในการแพทย์อยู่" },
            { en: "My thesis focuses on using computer vision to detect abnormalities in medical images.", th: "วิทยานิพนธ์ของฉันเน้นการใช้ computer vision ตรวจหาความผิดปกติในภาพทางการแพทย์" },
            { en: "I'm looking for an internship in AI or data analytics.", th: "ฉันกำลังหาอินเทิร์นในสาย AI หรือ data analytics อยู่" },
            { en: "The biggest challenge was cleaning and preprocessing the dataset.", th: "ความท้าทายที่ใหญ่ที่สุดคือการทำความสะอาดและเตรียมข้อมูล" },
            { en: "I presented my project and got some really useful feedback.", th: "ฉัน present โปรเจกต์ไปและได้รับ feedback ที่มีประโยชน์มากๆ" },
            { en: "Have you heard of large language models like GPT?", th: "คุณเคยได้ยินเรื่อง large language models อย่าง GPT ไหม?" },
            { en: "The results suggest that the second approach performs significantly better.", th: "ผลลัพธ์บ่งชี้ว่าแนวทางที่สองให้ประสิทธิภาพดีกว่าอย่างมีนัยสำคัญ" },
            { en: "I need to evaluate the model using cross-validation.", th: "ฉันต้องประเมินโมเดลด้วย cross-validation" },
            { en: "Can you help me understand how to interpret this confusion matrix?", th: "ช่วยฉันเข้าใจวิธีอ่าน confusion matrix นี้ได้ไหม?" },
            { en: "I think the problem might be related to imbalanced data.", th: "ฉันคิดว่าปัญหาอาจเกี่ยวกับข้อมูลที่ไม่สมดุล" },
            { en: "My goal is to eventually work on medical AI applications.", th: "เป้าหมายของฉันคือได้ทำงานด้าน medical AI ในอนาคต" },
        ]
    },
    {
        id: 'B23', title: 'B. คุยกับ Professor / TA ต่างชาติ', color: 'bg-sky-50 border-sky-200 text-sky-900',
        sentences: [
            { en: "Excuse me, Professor — do you have a moment to talk?", th: "ขอโทษนะครับ/ค่ะ อาจารย์ — พอมีเวลาคุยนิดนึงไหมครับ/ค่ะ?" },
            { en: "I'm a bit confused about the assignment instructions.", th: "ฉันงงเรื่องคำแนะนำของงานนิดหน่อยครับ/ค่ะ" },
            { en: "Would it be okay to submit the assignment a day late?", th: "โอเคไหมถ้าจะส่งงานช้าไปหนึ่งวัน?" },
            { en: "I wanted to ask if we can work in pairs for this project.", th: "อยากถามว่าโปรเจกต์นี้ทำเป็นคู่ได้ไหมครับ/ค่ะ?" },
            { en: "I'm not sure I understood the feedback on my last assignment.", th: "ฉันไม่แน่ใจว่าเข้าใจ feedback งานที่แล้วถูกต้องไหม" },
            { en: "Could you explain the grading criteria in more detail?", th: "ช่วยอธิบายเกณฑ์การให้คะแนนให้ละเอียดขึ้นหน่อยได้ไหมครับ/ค่ะ?" },
            { en: "I'd like to discuss my thesis topic with you if possible.", th: "อยากขอนัดคุยเรื่องหัวข้อวิทยานิพนธ์กับอาจารย์ถ้าเป็นไปได้ครับ/ค่ะ" },
            { en: "I missed the last class due to a health issue — did I miss anything important?", th: "ฉันขาดเรียนครั้งที่แล้วเพราะไม่สบาย มีอะไรสำคัญที่พลาดไปไหมครับ/ค่ะ?" },
            { en: "Is it okay to ask questions during the lecture?", th: "ถามคำถามระหว่างเรียนได้ไหมครับ/ค่ะ?" },
            { en: "I'd appreciate any additional resources you could recommend.", th: "ขอบคุณมากเลยถ้าอาจารย์จะแนะนำแหล่งข้อมูลเพิ่มเติมให้" },
            { en: "I've been struggling with this concept — could you walk me through it?", th: "ฉันสงสัยกับ concept นี้มาสักพักแล้ว อาจารย์พอจะอธิบายทีละขั้นได้ไหมครับ/ค่ะ?" },
            { en: "When are your office hours this week?", th: "สัปดาห์นี้ office hours ของอาจารย์อยู่ช่วงไหนครับ/ค่ะ?" },
            { en: "Thank you for your feedback — I'll revise it right away.", th: "ขอบคุณสำหรับ feedback นะครับ/ค่ะ จะรีบแก้ให้เลย" },
            { en: "I sent you an email last week but haven't heard back yet.", th: "ฉันส่งอีเมลให้อาจารย์อาทิตย์ที่แล้วแต่ยังไม่ได้รับการตอบกลับครับ/ค่ะ" },
            { en: "Could I have an extension on the deadline? I've been sick.", th: "ขอเลื่อนกำหนดส่งได้ไหมครับ/ค่ะ? ฉันไม่สบายอยู่" },
            { en: "I find the material really challenging but also very interesting.", th: "เนื้อหาท้าทายมากเลยครับ/ค่ะ แต่ก็น่าสนใจมากด้วย" },
            { en: "I just wanted to say thank you for a great semester.", th: "อยากบอกขอบคุณสำหรับเทอมที่ผ่านมานะครับ/ค่ะ" },
            { en: "I'm applying for an internship and was wondering if you could write me a recommendation.", th: "ฉันกำลังสมัครอินเทิร์นอยู่ อาจารย์พอจะเขียน recommendation letter ให้ได้ไหมครับ/ค่ะ?" },
            { en: "Is this going to be on the exam?", th: "เรื่องนี้จะออกข้อสอบไหมครับ/ค่ะ?" },
            { en: "I'd like to take your elective next semester if there's still space.", th: "ฉันอยากลงวิชาเลือกของอาจารย์เทอมหน้าถ้ายังมีที่ว่างอยู่ครับ/ค่ะ" },
        ]
    },
    {
        id: 'C23', title: 'C. สุขภาพ & คลินิก / โรงพยาบาล', color: 'bg-rose-50 border-rose-200 text-rose-900',
        sentences: [
            { en: "I'd like to make an appointment with a doctor.", th: "ขอนัดหมอหน่อยได้ไหมครับ/ค่ะ?" },
            { en: "I've had a headache since yesterday morning.", th: "ฉันปวดหัวมาตั้งแต่เมื่อเช้าวาน" },
            { en: "I have a sore throat and a slight fever.", th: "ฉันเจ็บคอกับมีไข้เล็กน้อย" },
            { en: "I've been feeling dizzy and nauseous all day.", th: "ฉันรู้สึกวิงเวียนและคลื่นไส้ทั้งวันเลย" },
            { en: "I think I pulled a muscle in my back.", th: "ฉันคิดว่ากล้ามเนื้อหลังฉีก" },
            { en: "How long have you been experiencing these symptoms?", th: "คุณมีอาการพวกนี้มานานแค่ไหนแล้วครับ/ค่ะ?" },
            { en: "I'm allergic to penicillin.", th: "ฉันแพ้ยาเพนิซิลิน" },
            { en: "Do I need a prescription for this medication?", th: "ยาชนิดนี้ต้องมีใบสั่งยาไหมครับ/ค่ะ?" },
            { en: "How many times a day should I take this?", th: "กินยานี้วันละกี่ครั้งครับ/ค่ะ?" },
            { en: "Should I come back for a follow-up appointment?", th: "ต้องนัดติดตามอาการอีกครั้งไหมครับ/ค่ะ?" },
            { en: "I haven't been sleeping well for the past two weeks.", th: "ฉันนอนไม่ค่อยหลับมาสองอาทิตย์แล้ว" },
            { en: "The pain started in my stomach and spread to my side.", th: "ความเจ็บปวดเริ่มที่ท้องแล้วลามมาที่ข้าง" },
            { en: "I don't have a fever, but I feel exhausted.", th: "ฉันไม่มีไข้ แต่รู้สึกอ่อนเพลียมาก" },
            { en: "Is this serious, or will it go away on its own?", th: "อาการนี้น่าเป็นห่วงไหม หรือมันจะหายไปเองได้?" },
            { en: "The doctor said I need to rest for a few days.", th: "หมอบอกว่าต้องพักสักสองสามวัน" },
            { en: "I'd like a refill on my prescription, please.", th: "ขอรับยาเดิมต่อหน่อยได้ไหมครับ/ค่ะ?" },
            { en: "I've been under a lot of stress lately and I think it's affecting my health.", th: "ช่วงนี้เครียดมาก และรู้สึกว่ามันกระทบสุขภาพด้วย" },
            { en: "Where is the nearest pharmacy from here?", th: "ร้านขายยาที่ใกล้ที่สุดอยู่ที่ไหนจากที่นี่ครับ/ค่ะ?" },
            { en: "Can I get this checked out without an appointment?", th: "ขอตรวจได้เลยโดยไม่ต้องนัดล่วงหน้าได้ไหมครับ/ค่ะ?" },
            { en: "I think I need to see a specialist.", th: "ฉันคิดว่าต้องไปหาหมอเฉพาะทาง" },
        ]
    },
    {
        id: 'D23', title: 'D. ร้านอาหาร & สั่งอาหาร', color: 'bg-orange-50 border-orange-200 text-orange-900',
        sentences: [
            { en: "I'd like to reserve a table for two, please.", th: "ขอจองโต๊ะสำหรับสองคนหน่อยได้ไหมครับ/ค่ะ?" },
            { en: "Could I see the menu, please?", th: "ขอดูเมนูหน่อยได้ไหมครับ/ค่ะ?" },
            { en: "What do you recommend today?", th: "วันนี้มีอะไรแนะนำบ้างครับ/ค่ะ?" },
            { en: "I'll have the grilled salmon and a glass of water, please.", th: "ขอแซลมอนย่างกับน้ำเปล่าแก้วนึงครับ/ค่ะ" },
            { en: "Does this dish contain peanuts? I have a nut allergy.", th: "จานนี้มีถั่วลิสงไหมครับ/ค่ะ? ฉันแพ้ถั่ว" },
            { en: "Could I get this without the sauce?", th: "ขอแบบไม่ใส่ซอสได้ไหมครับ/ค่ะ?" },
            { en: "Is there a vegetarian option available?", th: "มีเมนูมังสวิรัติด้วยไหมครับ/ค่ะ?" },
            { en: "Excuse me — I think there's a mistake in my order.", th: "ขอโทษนะครับ/ค่ะ คิดว่าออร์เดอร์ฉันผิด" },
            { en: "This isn't what I ordered — I asked for the pasta.", th: "อันนี้ไม่ใช่ที่ฉันสั่งนะครับ/ค่ะ ฉันสั่งพาสต้า" },
            { en: "Could we get some extra napkins, please?", th: "ขอกระดาษทิชชูเพิ่มหน่อยได้ไหมครับ/ค่ะ?" },
            { en: "We're ready to order.", th: "พวกเราพร้อมสั่งแล้วครับ/ค่ะ" },
            { en: "Can we have the bill, please?", th: "ขอบิลหน่อยได้ไหมครับ/ค่ะ?" },
            { en: "Could we pay separately?", th: "แยกบิลได้ไหมครับ/ค่ะ?" },
            { en: "The food was excellent — compliments to the chef.", th: "อาหารอร่อยมากเลยครับ/ค่ะ ฝากชมพ่อครัวด้วยนะ" },
            { en: "Do you accept credit card, or is it cash only?", th: "รับบัตรเครดิตไหมครับ/ค่ะ หรือจ่ายเงินสดเท่านั้น?" },
        ]
    },
    {
        id: 'E23', title: 'E. ช้อปปิ้ง & ต่อรอง', color: 'bg-yellow-50 border-yellow-200 text-yellow-900',
        sentences: [
            { en: "Do you have this in a larger size?", th: "มีขนาดที่ใหญ่กว่านี้ไหมครับ/ค่ะ?" },
            { en: "Can I try this on?", th: "ขอลองใส่ได้ไหมครับ/ค่ะ?" },
            { en: "How much is this?", th: "ชิ้นนี้ราคาเท่าไหร่ครับ/ค่ะ?" },
            { en: "Is this on sale right now?", th: "ตอนนี้มีโปรโมชันไหมครับ/ค่ะ?" },
            { en: "That's a bit more than I was hoping to spend.", th: "มันแพงกว่าที่คิดไว้นิดนึงครับ/ค่ะ" },
            { en: "Would you be willing to lower the price a little?", th: "ลดราคาให้นิดนึงได้ไหมครับ/ค่ะ?" },
            { en: "I'd like to return this — it doesn't fit.", th: "ขอคืนอันนี้ได้ไหมครับ/ค่ะ ใส่ไม่พอดี" },
            { en: "Do you have a return policy?", th: "มีนโยบายรับคืนสินค้าไหมครับ/ค่ะ?" },
            { en: "I bought this two days ago and it's already broken.", th: "ฉันซื้อมาสองวันก่อนแล้วมันก็พังแล้ว" },
            { en: "Could I exchange this for a different colour?", th: "ขอเปลี่ยนเป็นสีอื่นได้ไหมครับ/ค่ะ?" },
            { en: "I'll think about it and come back.", th: "ขอคิดดูก่อนนะครับ/ค่ะ แล้วจะกลับมา" },
            { en: "Do you do free shipping for orders over a certain amount?", th: "มีบริการส่งฟรีถ้าสั่งเกินจำนวนที่กำหนดไหมครับ/ค่ะ?" },
            { en: "I saw a cheaper version of this online.", th: "ฉันเห็นเวอร์ชันที่ถูกกว่านี้ออนไลน์" },
            { en: "Can I pay in installments?", th: "ผ่อนชำระได้ไหมครับ/ค่ะ?" },
            { en: "I'll take it — can you wrap it as a gift?", th: "เอาเลยครับ/ค่ะ ห่อเป็นของขวัญให้ด้วยได้ไหม?" },
        ]
    },
    {
        id: 'F23', title: 'F. อธิบายวัฒนธรรม & อาหารไทยให้ต่างชาติ', color: 'bg-emerald-50 border-emerald-200 text-emerald-900',
        sentences: [
            { en: "Thai food is known for its balance of sweet, sour, salty, and spicy flavours.", th: "อาหารไทยโด่งดังเรื่องความสมดุลของรสหวาน เปรี้ยว เค็ม และเผ็ด" },
            { en: "Pad Thai is basically stir-fried noodles with egg, bean sprouts, and peanuts.", th: "ผัดไทยก็คือเส้นผัดกับไข่ ถั่วงอก และถั่วลิสง" },
            { en: "If you can't handle spice, just tell them 'mai pet' — it means 'not spicy'.", th: "ถ้ากินเผ็ดไม่ได้ บอกว่า 'ไม่เผ็ด' ได้เลย แปลว่าไม่เอาเผ็ด" },
            { en: "Songkran is the Thai New Year — it's basically a huge water fight festival.", th: "สงกรานต์คือวันปีใหม่ไทย โดยพื้นฐานแล้วมันคือเทศกาลสาดน้ำขนาดใหญ่" },
            { en: "Wai is the traditional Thai greeting — you press your palms together and bow your head slightly.", th: "ไหว้คือการทักทายแบบดั้งเดิมของไทย ประกบมือแล้วก้มหัวเล็กน้อย" },
            { en: "The temple is called 'Wat' in Thai — there are thousands of them across the country.", th: "วัดในภาษาไทยเรียกว่า 'วัด' มีหลายพันแห่งทั่วประเทศ" },
            { en: "Street food in Thailand is amazing and surprisingly cheap.", th: "อาหารข้างทางในไทยอร่อยมากและราคาถูกน่าประหลาดใจ" },
            { en: "Som tam is a spicy papaya salad — it's one of the most popular Thai dishes.", th: "ส้มตำคือสลัดมะละกอเผ็ด เป็นหนึ่งในอาหารไทยที่ได้รับความนิยมมากที่สุด" },
            { en: "Thai people eat rice with almost every meal — it's a staple here.", th: "คนไทยกินข้าวแทบทุกมื้อ มันคืออาหารหลักที่นี่" },
            { en: "Loy Krathong is a lantern and floating festival held in November.", th: "ลอยกระทงเป็นเทศกาลโคมลอยและกระทง จัดในเดือนพฤศจิกายน" },
            { en: "Thai people generally place a high value on respect and politeness.", th: "คนไทยโดยทั่วไปให้ความสำคัญกับความเคารพและความสุภาพมาก" },
            { en: "The Grand Palace is probably the most famous landmark in Bangkok.", th: "พระบรมมหาราชวังน่าจะเป็น landmark ที่โด่งดังที่สุดในกรุงเทพ" },
            { en: "If you visit Thailand, make sure you try mango sticky rice — it's incredible.", th: "ถ้ามาเที่ยวไทย อย่าลืมลองข้าวเหนียวมะม่วงนะ มันอร่อยมากจริงๆ" },
            { en: "Thai script looks very different from English, but there are classes if you want to learn.", th: "อักษรไทยดูแตกต่างจากภาษาอังกฤษมาก แต่มีคลาสเรียนถ้าอยากเรียน" },
            { en: "Thailand has three main seasons: hot, rainy, and cool — there's no winter here.", th: "ไทยมีสามฤดูหลัก คือร้อน ฝน และเย็น ที่นี่ไม่มีหน้าหนาว" },
        ]
    },
    {
        id: 'G23', title: 'G. LinkedIn / Email สมัครงาน & Cover Letter', color: 'bg-slate-50 border-slate-200 text-slate-800',
        sentences: [
            { en: "I am writing to express my interest in the junior data scientist position.", th: "ดิฉัน/ผมเขียนมาเพื่อแสดงความสนใจในตำแหน่ง junior data scientist" },
            { en: "I believe my skills and experience make me a strong candidate for this role.", th: "เชื่อว่าทักษะและประสบการณ์ของดิฉัน/ผมทำให้เป็นผู้สมัครที่เหมาะสมสำหรับตำแหน่งนี้" },
            { en: "I have hands-on experience with Python, data analysis, and machine learning.", th: "ดิฉัน/ผมมีประสบการณ์ลงมือทำจริงด้าน Python, data analysis และ machine learning" },
            { en: "I am a highly motivated and detail-oriented individual.", th: "ดิฉัน/ผมเป็นคนที่มีแรงจูงใจสูงและใส่ใจในรายละเอียด" },
            { en: "I am currently pursuing a degree in AI engineering and data science.", th: "ปัจจุบันกำลังศึกษาระดับปริญญาด้านวิศวกรรม AI และดาต้าซายน์อยู่" },
            { en: "I would welcome the opportunity to discuss how I can contribute to your team.", th: "ยินดีมากถ้าจะมีโอกาสได้คุยว่าจะช่วยอะไรทีมของคุณได้บ้าง" },
            { en: "Please find my CV and portfolio attached to this email.", th: "โปรดดู CV และ portfolio ของดิฉัน/ผมที่แนบมากับอีเมลนี้" },
            { en: "I look forward to the possibility of working with your team.", th: "หวังเป็นอย่างยิ่งว่าจะมีโอกาสได้ทำงานร่วมกับทีมของคุณ" },
            { en: "I am available for an interview at your earliest convenience.", th: "ดิฉัน/ผมพร้อมสำหรับการสัมภาษณ์เมื่อคุณสะดวก" },
            { en: "Thank you for considering my application.", th: "ขอบคุณที่พิจารณาการสมัครของดิฉัน/ผม" },
            { en: "I wanted to follow up on my application submitted last week.", th: "อยากติดตามผลใบสมัครที่ส่งไปอาทิตย์ที่แล้วครับ/ค่ะ" },
            { en: "Could you let me know the status of my application?", th: "ช่วยแจ้งสถานะของใบสมัครของดิฉัน/ผมได้ไหมครับ/ค่ะ?" },
            { en: "I have attached my updated resume as requested.", th: "ดิฉัน/ผมแนบ resume ที่อัปเดตแล้วมาตามที่ขอไว้" },
            { en: "I am excited about the opportunity to grow with your company.", th: "ตื่นเต้นมากกับโอกาสที่จะเติบโตไปพร้อมกับบริษัทของคุณ" },
            { en: "My long-term goal is to contribute to impactful AI projects in the healthcare sector.", th: "เป้าหมายระยะยาวของดิฉัน/ผมคือการมีส่วนร่วมในโปรเจกต์ AI ที่สร้างผลกระทบในด้านสาธารณสุข" },
            { en: "I am a quick learner and I thrive in fast-paced environments.", th: "ดิฉัน/ผมเรียนรู้ได้เร็วและทำงานได้ดีในสภาพแวดล้อมที่เร็วและมีความท้าทาย" },
            { en: "I have experience leading a team of four on a six-month data project.", th: "ดิฉัน/ผมมีประสบการณ์นำทีมสี่คนในโปรเจกต์ข้อมูลระยะหกเดือน" },
            { en: "I would love to learn more about the role and the team culture.", th: "อยากรู้เพิ่มเติมเกี่ยวกับตำแหน่งนี้และวัฒนธรรมของทีม" },
            { en: "My strongest skills are in Python programming and data visualization.", th: "ทักษะที่แข็งแกร่งที่สุดของดิฉัน/ผมคือการเขียนโปรแกรม Python และ data visualization" },
            { en: "I look forward to hearing from you regarding next steps.", th: "หวังว่าจะได้รับการติดต่อเรื่องขั้นตอนต่อไปจากคุณ" },
        ]
    },
    {
        id: 'H23', title: 'H. การเงิน & ธนาคาร', color: 'bg-indigo-50 border-indigo-200 text-indigo-900',
        sentences: [
            { en: "I'd like to open a savings account.", th: "ขอเปิดบัญชีออมทรัพย์หน่อยได้ไหมครับ/ค่ะ?" },
            { en: "I need to transfer money to another account.", th: "ฉันต้องโอนเงินไปยังบัญชีอื่น" },
            { en: "My card was declined — I'm not sure why.", th: "บัตรของฉันถูกปฏิเสธ ไม่รู้ว่าเพราะอะไร" },
            { en: "I think there's an unauthorized charge on my account.", th: "ฉันคิดว่ามีการเรียกเก็บเงินที่ไม่ได้รับอนุญาตในบัญชีของฉัน" },
            { en: "Could you tell me what the current exchange rate is?", th: "ช่วยบอกอัตราแลกเปลี่ยนปัจจุบันได้ไหมครับ/ค่ะ?" },
            { en: "I need to set up automatic bill payments.", th: "ฉันต้องตั้งค่าชำระบิลอัตโนมัติ" },
            { en: "What are the fees for international transfers?", th: "ค่าธรรมเนียมสำหรับการโอนเงินระหว่างประเทศเป็นเท่าไหร่?" },
            { en: "I'd like to dispute a charge on my statement.", th: "ฉันต้องการโต้แย้งรายการเรียกเก็บในใบแจ้งยอด" },
            { en: "My card was lost — I need to report it immediately.", th: "บัตรของฉันหาย ต้องรายงานทันทีเลย" },
            { en: "I've been saving a portion of my salary every month.", th: "ฉันเก็บเงินส่วนหนึ่งจากเงินเดือนทุกเดือน" },
            { en: "I'm trying to manage my expenses better this year.", th: "ปีนี้ฉันพยายามจัดการค่าใช้จ่ายให้ดีขึ้น" },
            { en: "Can I check my balance online?", th: "เช็คยอดเงินออนไลน์ได้ไหมครับ/ค่ะ?" },
            { en: "I'd like to apply for a student loan.", th: "ฉันต้องการสมัครสินเชื่อนักศึกษา" },
            { en: "How long does an international transfer usually take?", th: "การโอนเงินระหว่างประเทศปกติใช้เวลานานแค่ไหน?" },
            { en: "I'm trying to build an emergency fund.", th: "ฉันกำลังพยายามสร้างกองทุนฉุกเฉิน" },
        ]
    },
];

window.ESB_Sessions.push({
    id: 'session-2-3',
    title: 'Session 2.3: Thai Context & Personal Scenarios',
    data: Part23Data,
    defaultOpen: false
});


